### ISSUE TITLE
Replacement for make.args function?

### ISSUE THREAD

**Issue by jcoliver** [jamiemkass/ENMeval#100]
The `make.args()` does not appear in the latest version (>=2.0.1). Do you have recommendations for updating legacy code that used `make.args()` to package arguments for `dismo::maxent()`? At this point, I'm cludging together a `list` based on the old source for `make.args()`...

**Comment by jamiemkass** [comment]
The `make.args()` function was used internally by `ENMevaluate()` to specify the arguments for maxent.jar.  This has been replaced with `enm.maxent.jar$args()`, a helper function for the ENMdetails object specifying maxent.jar, also used internally. The `args()` function inside the ENMdetails object is like a generic `make.args()` for any specified algorithm. Not sure what your application is, but if you could provide details on what you need to do, I can advise.

**Comment by jcoliver** [comment]
The general workflow is to use cross-validation on subsets of data to find the best model, then throw the full dataset at maxent, using that best model for predictions.

Snippet of legacy, where `env_data` are bioclimatic variables, `full_data[1, 2]` holds lat/long data:
```
maxent.args <- ENMeval::make.args(RMvalues = rm_best, fc = FC_best)
full_mod = maxent(env_data, as.matrix(full_data[,1:2]), args = maxent.args[[1]])
```
Values passed to `make.args()` are coming from the `results` slot of an ENMevaluation object (although `FC_best` is attempting to pull from the `features` column, which, upon further investigation, may not exist).

**Comment by jamiemkass** [comment]
I see, thanks for the explanation. If you want to use the model with optimal settings trained on the full dataset, you don't need to refit it because the `ENMevaluation` object stores them in `x@models`, where `x` is the object returned from `ENMevaluate()`. Models fit with subsets for cross-validation are only used to calculate stats but not stored.

**Comment by jcoliver** [comment]
Rock on. We'll update our code. Thanks for the suggestion and thanks for the package!
