### ISSUE TITLE
Arguments imply differing number of rows

### ISSUE THREAD

**Issue by cmontalvo-mancheno** [jamiemkass/ENMeval#102]
Based on a user-defined 7-fold cross validation, I want to select the best model across a suite of feature combinations and regularization multiplier values to predict the distribution of species in a different biogeographic region of mainland Tasmania. 

In this example, the target bioregion is BEL, so I assigned species occurrences and background points to a fold based on their intersection with the other seven bioregions of mainland Tasmania (i.e., FUR, KIN, TCH, TNS, TSE, TSR, and TWE). Yet, when I ran this code, I got an error message stating that “arguments imply differing number of rows: 12280, 0” (see attached screenshot).

Could this error be because folds have different number of occurrences? Or should I set the partitions argument to another option than “user”?

![image](https://user-images.githubusercontent.com/81724937/130377982-7179e897-4c66-47fc-89a9-a9aa84514444.png)

**Comment by jamiemkass** [comment]
Can you confirm that each of these bioregion partitions has >0 occurrence records? If one of them is missing occurrences, you would get this error, I think.

**Comment by jamiemkass** [comment]
How is spatial_block defined? It should be integers. Could this be the issue? If not, I might ask to take a look at a sample of the data.

**Comment by cmontalvo-mancheno** [comment]
I redefined the spatial_block from double to integer. Yet, the error still persists (please see attached screenshot). I am happy to share with you the data for this example. Please let me know if the files highlighted in the screenshot is what you need so I can email you the zip file containing the data.

![image](https://user-images.githubusercontent.com/81724937/130521284-8850dbeb-7eeb-4098-9698-675e40acc68a.png)

**Comment by jamiemkass** [comment]
Sorry, double type should work too. I thought they may be characters, which I've never tested. Yes, please send me the data and I'll investigate.

**Comment by cmontalvo-mancheno** [comment]
Thanks for your offer! While preparing the data, I realized that my environmental predictors (i.e., bioreg_08) was not the right RasterStack object. I change it to the right file, and the function run without any problem.

I apologize for opening an issue when there was no. As I am new to all this, I am not sure what I need to do to remove/delete this unnecessary issue.

Cheers,
Cristian

**Comment by jamiemkass** [comment]
Cristian, no worries at all! Actually, this info is useful to archive in case anyone else has the same problem. Glad you got it to work. I'll close this issue now, but please make a new one in case you run into other difficulties.

Jamie
