### ISSUE TITLE
ENMEvaluate() can only handle one categorical variable when a raster stack is used

### ISSUE THREAD

**Issue by joshbanta** [jamiemkass/ENMeval#103]
Hello, the new version of ENMEvaluate can only handle 1 categorical variable, at least when a raster stack is used.

Here is my code:

occs <- read.csv(file.path(system.file(package="dismo"), "/ex/bradypus.csv"))[,2:3]
envs <- raster::stack(list.files(path=paste(system.file(package="dismo"), "/ex", sep=""), pattern="grd", full.names=TRUE))

##add biome, which is layer 9, again. This is to act as a pretend second categorical variable
envs2 <- addLayer(envs, unstack(envs)[9])

tune.args <- list(fc = c("L","LQ","LQH","H"), rm = 1:5)
os <- list(abs.auc.diff = FALSE, pred.type = "logistic", validation.bg = "partition")
ps <- list(orientation = "lat_lat")

e <- ENMevaluate(occs, envs2, tune.args = tune.args, partitions = "block", other.settings = os, partition.settings = ps, algorithm = "maxnet", categoricals = c("biome.1", "biome.2"), overlap = TRUE)

Here is the error:

*** Running initial checks... ***

* Found 10 raster cells that were NA for one or more, but not all, predictor variables. Converting these cells to NA for all predictor variables.
* Removed 22 occurrence localities that shared the same grid cell.
* Assigning variable biome.1 to categorical ...
* Assigning variable biome.2 to categorical ...
* Clamping predictor variable rasters...
* Model evaluations with spatial block (4-fold) cross validation and lat_lat orientation...

*** Running ENMeval v2.0.0 with maxnet from maxnet package v0.1.4 ***

  |====                                                                                     |   5%Error in `[.data.frame`(out, , names(orig.vals)) : 
  undefined columns selected
In addition: Warning message:
In names(out)[ncol(out)] <- categoricals :
  number of items to replace is not a multiple of replacement length

**Comment by jamiemkass** [comment]
@joshbanta, thanks so much for alerting me about this bug. The problem was that the `clamp.vars()` function was designed for single categorical variables only (an oversight), but I fixed this so it can handle more than one. I also added some new unit tests to make sure multiple categorical variables work okay.

Please try the new version 2.0.2 and confirm that it works with your dataset.

Jamie

**Comment by jamiemkass** [comment]
Would you be able to send me a sample of your data so I can try and diagnose? Thanks~

**Comment by jasonbmackenzie** [comment]
Sure. The (floristic) categorical vars are ~2Mb each, whereas the continuous vars are ~25-50Mb each. The full raster stack is > 200Mb. How much do you need?

**Comment by jasonbmackenzie** [comment]
Thanks for the quick troubleshoot! That's good news for others, but a weird result for me? I'm running the dev v2.0.2 from Github. The full tuning completes if I include 0-1 categorical vars, but mine continues to fall over ('stack' error above) if I include them all (n=6)?

**Comment by jamiemkass** [comment]
Does it say "ENMeval 2.0.2" when you run ENMevaluate()? I ask because if
you installed the new version but did not start a new session, it might not
have loaded 2.0.2 correctly. Just trying to make sure this is not the
issue. Thanks.

**Comment by jasonbmackenzie** [comment]
Thanks for checking, but my R packages are up to date. I doubt this matters, but my versions of R (4.0.2), RStudio (1.3.1073) and Windows (10 Pro Build 19043) are all a bit behind the latest available.

Below is an example of how my successful ENMevaluate() runs initiate (i.e., using 1 categorical var): 
*** Running initial checks ... ***
* Assigning variable Floristics_ACACspp to categorical ...
* Clamping predictor variable rasters...
* Model evaluations with random 5-fold cross validation...
*** Running ENMeval v2.0.2 with maxent.jar v3.4.4 from dismo package v1.3.5 ***
...

**Comment by jamiemkass** [comment]
Okay, thanks for confirming. I can try testing a bit more and get back to you if I find anything. One possible option for now is combining the categoricals into a single layer, which will work as long as there is no overlap between them.
