### ISSUE TITLE
extract data for response curves

### ISSUE THREAD

**Issue by scbrown86** [jamiemkass/ENMeval#104]
Is there anyway to extract the data used to plot the response curves? I'd like to make the curves in ggplot rather than base graphics, but not sure how to extract the required data.

**Comment by jamiemkass** [comment]
Do you mean the predictor variable response curves? You can generate those with `dismo::response(m)`, where m is a model object you can find in `results@models` from `ENMevaluate()`. If you set the output to a variable, I am pretty sure that saves the data frame you can use to then plot the data as you wish.
