### ISSUE TITLE
ENMnulls() error

### ISSUE THREAD

**Issue by jasonbmackenzie** [jamiemkass/ENMeval#108]
I derived an ENMevaluation object ('e.mx') where delta.AICc suggests 'LQHP_1' are the best tuning settings. I tried running ENMnulls() to do significance testing with random data and similar settings, but got an error? Code and error are pasted below. Any suggestions?

mod.null <- ENMnulls(e.mx, mod.settings=list(fc="LQHP", rm=1), no.iter=100,
                                    eval.stats=c("auc.val","auc.diff","cbi.val","or.mtp","or.10p"),
                                    parallel=TRUE, numCores=18, parallelType="doSNOW")

Building and evaluating null ENMs with 100 iterations...
  |                                                                                                 |   0%
Of 20 total cores using 18...
Running in parallel using doSNOW...
  |=======================================| 100%
Error in Ops.data.frame(emp.avgs, nulls.avgs) : 
  ‘-’ only defined for equally-sized data frames

**Comment by jamiemkass** [comment]
Looks like the error is occurring on line 282, which calculates the z-scores as `(emp.avgs - nulls.avgs) / nulls.sds`. Perhaps one of these values is NA for some reason? I could diagnose if you send me the data.

**Comment by jasonbmackenzie** [comment]
Thanks for the offer to diagnose, Jamie. ENMnulls() crashes before saving an output, so do you want me to send the ENMevaluation object ('e.mx' above)? If yes, RStudio says 'e.mx' is ~3.1Gb, but when I save.image(), the .rdata file is only ~800Mb? Given difference in file sizes, is anything relating to 'e.mx' held in memory, but not saved to file, which you will require?

**Comment by jasonbmackenzie** [comment]
I was able to replicate the error using only the 'e.mx' saved to disk, so I sent you a google drive link via gmail. thanks again for help with troubleshooting!
