### ISSUE TITLE
"index larger than maximal 170"

### ISSUE THREAD

**Issue by arpitdeomurari** [jamiemkass/ENMeval#109]
Hi Jamie,

I'm constantly running into errors with ENMEval 2.0.2, I had code developed for the earlier version but with this new and enhanced version (CBI) I have totally modified the code to suit the new version. 

Error 1: I have a good system with 64 GB RAM and 180 GB Pagefile on windows 10, When I use maxent.jar 3.4.4 it always gives me Java Heap memory error.

After dealing with maxent.jar and not being able to succeed in the running analysis after changing all java versions, installing/reinstalling, it's still giving me the same error, while the physical memory is still free.
Here is java option I have set.
options(java.parameters = "-XX:PermSize=256m -XX:MaxMetaspaceSize=2048m -XX:MaxPermSize=1024m -XX:InitialRAMPercentage=30.0 -XX:MaxRAMPercentage=95.0" )
Running ENMeval v2.0.2 for Bucanetes sp with maxent.jar 3.4.4 from dismo package v1.1.4

Error 2. as the second option I try with maxnet. I'm getting ""index larger than maximal 170""

As you suggested over here https://githubmemory.com/repo/jamiemkass/ENMeval/issues/81
I have tried to reread the raster file in memory but no luck.

Running ENMeval v2.0.2 for Bucanetes sp with maxnet from maxnet package v0.1.2

Is it a bug? Please do reply

Regards

**Comment by jamiemkass** [comment]
Sorry you're having issues. Not sure about your parameterization of the Java options, but I know that `options(java.parameters = "-Xmx1g" )` works to set the memory limit to 1 GB, for example, if you run this before loading dismo. If you have unwieldy rasters that are just too big, consider running ENMevaluate without rasters (consult the vignette for an example). I guess maxnet is having the same issue?
