### ISSUE TITLE
Issues with library(ENMeval) and library(raster)

### ISSUE THREAD

**Issue by ThomasBaker96** [jamiemkass/ENMeval#114]
Hi Jamie,

I am a graduate student working on species distribution models for wood turtles (Glyptemys insculpta). Last Spring, I used ENMeval to find out which Maxent parameters to use and to create bias files, and did not run into any problems. I am now returning to ENMeval to undertake a new round of modelling but I am running into an issue right from the get-go. When I try to load in ENMeval and raster, I recieve these errors: 

Error: package or namespace load failed for ‘ENMeval’:
 Function found when exporting methods from the namespace ‘raster’ which is not S4 generic: ‘all.equal’
In addition: Warning message:
no function found corresponding to methods exports from ‘raster’ for: ‘direction’, ‘gridDistance’

Error: package or namespace load failed for ‘raster’:
 Function found when exporting methods from the namespace ‘raster’ which is not S4 generic: ‘all.equal’
In addition: Warning message:
no function found corresponding to methods exports from ‘raster’ for: ‘direction’, ‘gridDistance’

This is the code I am trying to use:

install.packages("rJava", dependencies = TRUE)
install.packages("ENMeval", dependencies = TRUE)
install.packages("raster", dependencies = TRUE)

library(rJava)
library(ENMeval)
library(raster)
library(MASS)

All the package installations appeared to function properly and I had no problems with library(rJava) or library(MASS). It's just library(ENMeval) and library (raster) that give problems. I would appreciate any help in sorting this out.

Thank you, all the best,

**Comment by ThomasBaker96** [comment]
Hi Jamie, 

Thanks for the response. My version of R is updated to the most recent version (4.1.2 Bird Hippie) and I have now created a new project and session but am still running into the same error. 

All the best,

**Comment by ThomasBaker96** [comment]
Hi Jamie,

I have resolved the problem by installing RTools. I had not needed it in the past, but the raster package now seems to require it.

All the best,

**Comment by jamiemkass** [comment]
Ah, that's great to hear. I didn't think of RTools as the solution, but on Windows it often is.
