### ISSUE TITLE
ENMevaluate Dataframe Error

### ISSUE THREAD

**Issue by ThomasBaker96** [jamiemkass/ENMeval#115]
Hi Jamie again,

I now have a new error when I attempt to run the ENMevaluate function. This is the code I am running:

`enmeval_results <- ENMevaluate(occ, env, bg, tune.args = list(fc = c("L","LQ","H", "LQH", "LQHP", "LQHPT"), rm = 1:5), partitions = "randomkfold", partition.settings = list(kfolds = 10), algorithm = "maxnet", categoricals = c("size_nearest_watercourse_properextent_250m", "temp_nearest_watercourse_properextent_250m", "alk_nearest_watercourse_properextent_250m"))`

And this is the error I am receiving:

`Error in data.frame(auc.train = auc.train, cbi.train = cbi.train) : 
  arguments imply differing number of rows: 1, 0`

Any help with this would be much appreciated. 

All the best,

**Comment by ThomasBaker96** [comment]
It would probably be useful to also say that I receive this output before the error pops up: 

`*** Running initial checks... ***

* Found 1667 raster cells that were NA for one or more, but not all, predictor variables. Converting these cells to NA for all predictor variables.
* Removed 3 occurrence points with NA predictor variable values.
* Removed 9 background points with NA predictor variable values.
* Assigning variable size_nearest_watercourse_properextent_250m to categorical ...
* Assigning variable temp_nearest_watercourse_properextent_250m to categorical ...
* Assigning variable alk_nearest_watercourse_properextent_250m to categorical ...
* Clamping predictor variable rasters...
* Model evaluations with random 10-fold cross validation...

*** Running ENMeval v2.0.3 with maxnet from maxnet package v0.1.4 ***

  |=======                                                                                                                                                                                              |   3%`

**Comment by jamiemkass** [comment]
Recently, the package ecospat updated and changed the parameterization of ecospat.boyce(), which I use to calculate CBI. Please try reinstalling the new ecospat and see if that fixes it.

**Comment by ThomasBaker96** [comment]
I started a new session and reinstalled all the needed packages, but the error persists.

Thanks for the response.

**Comment by jamiemkass** [comment]
Something else to check is that each categorical has all the factor levels it started with when input to `ENMevaluate()` after the NA raster cells in the stack are removed. Looks like you have 1667 cells that are NA for at least one raster in your stack. Removing these cells could result in a categorical variable with missing classes, and I think if there is only one class an error occurs. There is an internal f unction called `rasStackNAs()` in R/utilities.R that makes all NA cells for one raster NA in all the other rasters. Use this and examine the factor levels of your rasters. I would also investigate why there are so many cells that are NA for one but not all rasters.

**Comment by ThomasBaker96** [comment]
I have gotten rasStackNAs() to work and harmonize all the NAs in my raster stack but ENMevaluate() still returns the same error. I had a similar situation with raster layers that had slight differences in their extents when I used the older version of ENMevaluate() back in Spring 2021 and ran into no such errors.

**Comment by jamiemkass** [comment]
Hm, I think the only thing we can do now is have me examine your data and do some troubleshooting. Would you be able to provide me with a data sample that reproduces your error?

**Comment by ThomasBaker96** [comment]
I could probably put something together and send it to you, what would be the best way to share files with you? I cannot share any of my occurrence data however as it is sensitive data. I could perhaps just create a random selection of points within my study area, would that suffice?

Thank you for the help!

**Comment by jamiemkass** [comment]
Awesome. Please send it to the email in my profile. Random occurrence points are fine. Just please confirm you have the same issues with them for sending.

**Comment by jamiemkass** [comment]
Thanks for sending the data. I've confirmed it was because the ecospat package was version 3.2 and not the new 3.2.1. Please start a new session, confirm that ecospat is 3.2.1 after installing, and try again.

Jamie

**Comment by jamiemkass** [comment]
By the way, looks like at least one layer has missing data for a river in the central-south. The top is the NAs in green for the original "alk_nearest_watercourse_properextent_250m" variable, the bottom is the one edited by ENMeval to remove the NAs that are shared across all rasters. Just something to be aware of.

<img width="745" alt="Screen Shot 2022-02-07 at 11 46 48" src="https://user-images.githubusercontent.com/2090459/152716703-98ff8248-de00-4ef9-bf4c-481c9914ff38.png">
<img width="741" alt="Screen Shot 2022-02-07 at 11 47 10" src="https://user-images.githubusercontent.com/2090459/152716739-577da54d-5e0a-4207-a4ef-0f03d754e1bd.png">

**Comment by ThomasBaker96** [comment]
Hi Jamie,

Great, thanks for troubleshooting that for me!

Thanks for highlighting the river that's being dropped too. I checked it out and it's a lake that isn't included in the provincial DEM that I am using. It's highly unlikely that it would be suitable habitat for my focal species so its omission is likely negligible.

All the best,

**Comment by ThomasBaker96** [comment]
Hi Jamie,

Making sure I had ecospat 3.2.1 got me past the 3% mark where the script was failing before but now I have received this error at 30%: 

`Error in mm %*% object$betas : non-conformable arguments`

Do you have a list of all the required packages that shows their most current versions so I can check to see how up-to-date mine are?

Thanks, all the best,

**Comment by ThomasBaker96** [comment]
All three of my categorical variables have three levels.

**Comment by jamiemkass** [comment]
So this would be a maxnet error, likely due to hinge features on a very complex model. I've seen this before. I would look into which set of features you're using at 30%, remove it, and try again. Usually, the model that errors is so complex you wouldn't want to select it anyway because it's overfit

**Comment by jamiemkass** [comment]
Note: maxent.jar usually does not error on these models, so you can try with that instead.

**Comment by ThomasBaker96** [comment]
Hi Jamie,

It was the hinge features only set that was breaking the script. I have removed that and now everything is working as intended. A model with only hinge features doesn't seem like it would have been useful anyway.

Thanks for all the help!

**Comment by MichaelTroutman** [comment]
Hi Jamie, 

I am a lab technician working on species distribution maps of butterflies in Yosemite National Park. I am having a similar issue where it gets to 50% and stops with the same error:

input: 
e.mxjar <- ENMevaluate(occs = Mod[[1]][[1]], tune.args = list(fc = "L", rm = 1:2), envs = rasters, bg = bg, algorithm = "maxent.jar", partitions = "block")
*** Running initial checks... ***

* Clamping predictor variable rasters...
* Model evaluations with spatial block (4-fold) cross validation and lat_lon orientation...

*** Running ENMeval v2.0.2 with maxent.jar v3.4.3 from dismo package v1.3.5 ***

  |==========================================================                                                           |  50%This is MaxEnt version 3.4.3 
Error in data.frame(auc.train = auc.train, cbi.train = cbi.train) : 
  arguments imply differing number of rows: 1, 0

I have tried running rasStackNAs() and it returned no errors. I have successfully run this data on the java version of Maxent with default settings but cannot run it in the ENMeval package. Any advice on how to proceed?

**Comment by jamiemkass** [comment]
This may a problem due to different version of `ecospat` and `ENMeval` -- please update to ENMeval 2.0.3 and ecospat 3.2.1 and see if this issue persists.

**Comment by jamiemkass** [comment]
Great to hear!
