### ISSUE TITLE
using terra::predict( ) with ENMeval model outputs?

### ISSUE THREAD

**Issue by jasonbmackenzie** [jamiemkass/ENMeval#117]
I am struggling with compatibility issues between the terra and ENMeval packages for generating predictions? Based on previous workflows with dismo::maxent( ) and raster::predict( ), I assumed I could use terra::predict( ) with ENMeval outputs, but maybe not? I gather my question is related to Issue #112, because my ultimate goal is model transfer - i.e., to derive multiple species predictions for both current and future scenarios (n=24).  

During tuning, I ran into memory issues using raster data, so I used a 'samples with data' approach (below).

```
tune.args <- list(fc=c("L","LQ","LQH","H","LQHP","LQHPT"), rm=1:5)
os        <- list(abs.auc.diff=TRUE, pred.type="logistic", validation.bg="partition")

e.swd     <- ENMevaluate(occs=occsSP.z, bg=bgSP.z, tune.args=tune.args, partitions='block',
                     algorithm='maxent.jar', other.settings=os, categoricals="TPI", doClamp=TRUE, 
                     overlap=TRUE, overlapStat=c("D","I"), user.eval=proc, 
                     parallel=TRUE, numCores=18, parallelType='doSNOW',
                     quiet=FALSE, progbar=TRUE, rasterPreds=NULL)

res <- eval.results(e.swd)

opt.seq <- res %>% 
  filter(or.10p.avg == min(or.10p.avg)) %>% 
  filter(auc.val.avg == max(auc.val.avg))

m  <- eval.models(e.swd)[[opt.seq$tune.args]]
```

After tuning, I tried using terra::predict( ) by importing the optimal 'maxent.jar' model (m) and my predictor stack (f1_envs), but the output is nonsense (i.e., a raster with erratic stripes)? 

```
f_m   <- "D:/out/tuning.rdata"        
   
attach(f_m); m <- m;  detach(paste0('file:', f_m), character.only=TRUE) 

p <- terra::predict(f1_envs, m)
```

Based on recommendations from Issue #112, and comments above, can you please confirm the code below is more appropriate for deriving scenario predictions with a 'maxent.jar' output from ENMevaluate( )? For each species, sounds like I need to clamp each scenario, then predict...

```
# extract observed predictor values for combined occurrence and background records
pts <- bind_rows(occsSP.z, bgSP.z)
v <- raster::extract(envs, pts, method = 'simple', na.rm = TRUE)

# clamp future scenario variables
f1_envs <- clamp.vars(f1_envs, v, left = NULL, right = NULL, categoricals = NULL)

# derive future scenario predictions using optimal model
p_f1 <- enm.maxnet@predict(m, f1_envs, NULL, list(args=c("outputformat=cloglog")))
```

**Comment by jasonbmackenzie** [comment]
Sorry about the crazy formatting of code above, I should have used 'add code' button! 

Just to clarify, I think my problem relates to a previous post -- Issue #112? I used the tuning analysis to ID an optimal model, with the ultimate aim of generating current and future predictions across a range of scenarios. The code above was simplified to a single scenario, because the outputs were not working, but I possibly need to change my approach based on other posts? I used maxent, not maxnet, for my tuning analysis. Is it possible to extract a maxent model and project across multiple future scenarios, or do I have to use maxnet in the tuning to do this?

**Comment by jasonbmackenzie** [comment]
FYI, an example of code from my tuning analysis is pasted below, in case it helps

`tune.args <- list(fc=c("L","LQ","LQH","H","LQHP","LQHPT"), rm=1:5)
os        <- list(abs.auc.diff=TRUE, pred.type="logistic", validation.bg="partition")

e.swd     <- ENMevaluate(occs=occsSP.z, bg=bgSP.z, tune.args=tune.args, partitions='block',
                     algorithm='maxent.jar', other.settings=os, categoricals="TPI", doClamp=TRUE, 
                     overlap=TRUE, overlapStat=c("D","I"), user.eval=proc, 
                     parallel=TRUE, numCores=18, parallelType='doSNOW',
                     quiet=FALSE, progbar=TRUE, rasterPreds=NULL)

res <- eval.results(e.swd)

opt.seq <- res %>% 
  filter(or.10p.avg == min(or.10p.avg)) %>% 
  filter(auc.val.avg == max(auc.val.avg))

mod.simple  <- eval.models(e.swd)[[opt.seq$tune.args]]`

**Comment by jamiemkass** [comment]
Hey @jasonbmackenzie, for maxent.jar models, just use dismo::predict() with args=c("outputformat=cloglog"). Don't use terra::predict() for this. 

The solution in issue #112 is for maxnet models because they have no native way to predict to rasters.

**Comment by jasonbmackenzie** [comment]
Hi @jamiemkass , thanks for the clarification! I got a bit confused between predict() functions in raster, terra and dismo.

Do I need to clamp all my predictor stacks prior to dismo::predict(), or is this internally specified in maxent.jar models when you include the 'doClamp=TRUE' flag in ENMevaluate()?

**Comment by jamiemkass** [comment]
No, the clamping happens when models used to make predictions only, i.e., they are not specified internally in the model. ENMeval will use clamping to make its cross-validation predictions, but any further predictions made with fitted models need to either invoke clamping (though default I think for maxent.jar) or use clamped variables derived with clamp.vars().

**Comment by jasonbmackenzie** [comment]
Thanks again! I didn't see anything in the model slots to specify clamp values, but just wanted to make sure   )

**Comment by jasonbmackenzie** [comment]
In case this helps others, clamp.vars( ) appears to work on a RasterStack (from raster), but not an equivalent SpatRaster (from terra). The error returned using a SpatRaster is pasted below...

```
Error in rowSums(is.na(orig.vals)) : 
  'x' must be an array of at least two dimensions
```

**Comment by jasonbmackenzie** [comment]
clamp.vars() works if i specify a single data.frame (e.g., 'v' above), but it crashes (error directly below) if I  loop on a list of data.frames. any suggestions?

```
Error in ref.vals[, -which(colnames(ref.vals) %in% categoricals)] : 
  incorrect number of dimensions
```

i'm using loops to get through lots of species and scenarios, because parallel processing has memory issues. i created lists to cycle on species, scenarios, models, clamping values etc. below is an example of my code, where clamp.vars() crashes using the list 'ref.vals[i]'.

```
species   <- list("species1", "species2", "species3") 
scenarios <- list("D:/in/future1/", "D:/in/future2/", "D:/in/future3/")
futures   <- list('future1', 'future2', 'future3')
ref.vals  <- list(v1, v2, v3)             # observed clamping values for species1-3
models    <- list(m1, m2, m3)             # optimal maxent models for species1-3
thresh    <- list(t1, t2, t3)             # suitability thresholds for species1-3


for (i in 1:length(species)) {
  
  for (j in 1:length(scenarios)) {
    
    message('reading predictors... ', species[i], ' ', futures[j])
    l      <- list.files(path=scenarios[j], pattern='.tif$', full.names=T )
    s      <- rast(l) 
    crs(s) <- "epsg:3577"
    envs   <- stack(s)
    
    message('clamping predictors... ', species[i], ' ', futures[j])
    envs.c   <- clamp.vars(envs, ref.vals[i], left=NULL, right=NULL, categoricals="TPI")
    
    message('deriving predictions for... ', species[i], ' ', futures[j])
    pl     <- dismo::predict(envs.c, models[i], factors="TPI", ext=envs, progress="text", args=c("outputformat=cloglog"))
    
    message('thresholding predictions for... ', species[i], ' ', futures[j])
    pb     <- pl >= thresh[i]
    
    message('writing... ', species[i], '   ', futures[j])
    names(pl) <- species[i]
    names(pb) <- species[i]
    raster::writeRaster(pl, paste0(names(pl), '_', futures[j],'_logistic.tif'), format="GTiff", overwrite=TRUE)
    raster::writeRaster(pb, paste0(names(pb), '_', futures[j],'_binary.tif'), format="GTiff", overwrite=TRUE) 
    
    rm(l, s, envs, envs.c, pl, pb)
    
  }
}

```
