### ISSUE TITLE
doClamp not working with maxent.jar

### ISSUE THREAD

**Issue by LuisEnriqueAngelesGonzalez** [jamiemkass/ENMeval#118]
Hello! 
I am having problems will extrapolating to future scenarios. Response curves of dismo show that the model is clamping even when I specify to extrapolate. Moreover outputs (suitability maps for future scenarios) seems to be the same, It doesnt matter if I specify doClamp = TRUE or FALSE. This seem to be an old problem of ENMeval (https://groups.google.com/g/MAXENT/c/VUZu3ja_Wp0). Is there a solution to this?
Thanks!

**Comment by jamiemkass** [comment]
Thanks for posting this. Can you please provide the code you used to run ENMevaluate? That will help me diagnose.

**Comment by LuisEnriqueAngelesGonzalez** [comment]
Thank you for such a quick response! I will upload the script. I will also ask for permission to share the data (I could generate random data though) but I hope that the script can be helpful to detect if a problem exists (or not).
[3_Calibration_Kass.txt](https://github.com/jamiemkass/ENMeval/files/8166310/3_Calibration_Kass.txt)

**Comment by LuisEnriqueAngelesGonzalez** [comment]
`# -------------------------------------------------------------------------
# Model calibration  ------------------------------------------------------
# -------------------------------------------------------------------------

e.mx.l <- ENMevaluate(occs = occ, envs = env, bg = bg, doClamp  = FALSE,
                      algorithm = 'maxent.jar', partitions = 'checkerboard1', 
                      tune.args = list(fc = c("LQ"), 
                                       rm = seq(1)))

# -------------------------------------------------------------------------
# Select model with the best results --------------------------------------
# -------------------------------------------------------------------------
res <- eval.results(e.mx.l)
write.csv(res, 'Results/all_results.csv')

opt.seq <- res %>% 
  filter(auc.val.avg > 0.80) %>%
  filter(or.10p.avg    < 0.11) %>% 
  filter(AICc == min(AICc))

# Response curves

select <- c("Bathymetry", "Sur_Sal_Mean", "Sur_Sal_Ran",  "Sur_Tem_Mean",
            "Sur_Vel_Mean")

# Plot response curves (they are always clamped for some reason)

for(i in seq_along(select))
{ 
  var  <- paste0(select[i])
  a    <- response(eval.models(e.mx.l)[[opt.seq$tune.args]], var = var, range = 'p',
                   ylim = c(0,1), rug = FALSE)
  # df   <- as.data.frame(a)
  # plot(a, type = 'l', col =  'red', lwd = 2, 
  #      xlab = var, ylab = 'suitability', ylim = c(0,1),
  #      xlim = c(min(df[,1]), max(df[,1])))
}

# Proyections (doClamp give the same results regardless of TRUE or FALSE)

for(i in seq_along(1:4))
{
  ras <- lapply(final_list[i], stack)
  pre <- dismo::predict(e.mx.l@models$fc.LQ_rm.1, ras[[1]])
  f   <- paste0('Results/', names[i], '.tif')
  writeRaster(pre, filename = f)
  plot(pre, col = oceColorsJet(10), zlim = c(0,1))
}
`

**Comment by jamiemkass** [comment]
Thanks a lot, and sorry for the wait. I was able to confirm that maxent.jar is indeed not freely extrapolating even when you tell it not to clamp from `dismo::predict()`. I emailed Steven Phillips and hopefully he will know what's wrong. Until then, can you use maxnet? The new changes I made make it easier to get raster predictions from maxnet models (check out the new example code in ?ENMevaluate).

**Comment by LuisEnriqueAngelesGonzalez** [comment]
Hi!
Yes I will  use maxnet, I hope you guys can find a solution to this soon. 
Cheers!

**Comment by jamiemkass** [comment]
So, after talking with Steven, I realized that this may be due to an older version of maxent.jar I was using (3.4.1). When I used the most up-to-date version (3.4.3), the clamping worked. However, after more testing, I found that maxnet was having trouble freely extrapolating. We are still working on this issue, but it's something to be aware of. If you could do some testing with 3.4.3 and maxnet and report back, it would certainly help. Thanks!

**Comment by LuisEnriqueAngelesGonzalez** [comment]
Will do! I will report as soon as I can!

**Comment by LuisEnriqueAngelesGonzalez** [comment]
Dear Jamie,
I am so sorry I took so long (one month and half); however, I have been outside my country and a little busy with work. Fortunately, I was working in another project where we wanted to use ENMeval, so I tested what you asked me. Results for maxnet are the same no matter if I specify doClamp = TRUE, or doClamp = FALSE. I am attaching the response curves. This platform didn't allow me to upload the asc files (I could send you the asc files to your email if you want). I must say that I noticed the same problem for maxent 3.4.3.
Is there a potential solution? Am I doing something wrong?


[Responses_curves_maxnet_extrapolate.pdf](https://github.com/jamiemkass/ENMeval/files/8711363/Responses_curves_maxnet_extrapolate.pdf)
[Responses_curve_maxnet_clamp.pdf](https://github.com/jamiemkass/ENMeval/files/8711364/Responses_curve_maxnet_clamp.pdf)
[Response_curves_maxent_clamp.pdf](https://github.com/jamiemkass/ENMeval/files/8711365/Response_curves_maxent_clamp.pdf)
[Response_curves_maxent_extrapolate.pdf](https://github.com/jamiemkass/ENMeval/files/8711366/Response_curves_maxent_extrapolate.pdf)

**Comment by jamiemkass** [comment]
Hey Luis, sorry for the gap in time between responses. I just did more testing today and confirmed that maxent.jar 3.4.3 does clamp as expected, but that maxnet does not. I reached out to Steven Phillips again, and hopefully he can look into it. Looking at response curves is not the best way to check for clamping behavior unless you extend the x-axis out, but this also depends on the way the response functions work (I've had issues before looking at extrapolation with them). A better way is to train a model on a very small extent, then project to a much larger one with clamping on and off, then subtract the rasters from each other and sum the differences. If you get something very different from 0, the predictions are very different. You can plot them too and inspect differences, etc.

I'll update here when Steven gets back to me.

**Comment by jamiemkass** [comment]
Sorry for the long wait, but Steven pointed something out to me -- when the only features are hinge features, turning clamping off does nothing because these features cannot be extrapolated anyway. However, when there is a mix of hinge and linear/quadratic features, turning clamping off does force extrapolation, and I've confirmed this in both maxent.jar and maxnet. Hope this clears everything up.

**Comment by LuisEnriqueAngelesGonzalez** [comment]
Hey Jamie, no problem I know you are a very busy guy! Thanks for the help!

**Comment by jamiemkass** [comment]
Glad we could resolve this.
