### ISSUE TITLE
maxent.jar error: outputformat=cloglog"

### ISSUE THREAD

**Issue by Gay-MC** [jamiemkass/ENMeval#122]
Hi Jamie
When I run this code using maxnet, it works perfectly:

> clim.mod.2.5LQ <- ENMevaluate(occs = hull.pts, envs = clim, bg = bg.CYP, 
                        algorithm = "maxnet", partitions = 'block', categoricals = NULL,
                        fc = "LQ", RMvalues=2.5, parallel = T)

However, I would like to use maxent.jar so that I can get permutation importance values. When I substitute "maxent.jar" for "maxnet", I get the following error.

*** Running ENMeval v2.0.3 with maxent.jar v3.3.3k from dismo package v1.3.5 ***
  |                                                                                                              |   0%
Of 8 total cores using 8...
Running in parallel using doSNOW...
  |==============================================================================================================| 100%Error in { : task 1 failed - "args not understood:
outputformat=cloglog"

Please note that although it says it is using maxent.jar v3.3.3k, I only have maxent.jar v3.4.4 on my machine, both in its own folder and in the dismo java folder.

I am not sure if this is a problem in ENMeval or dismo, but I have been able.

Thanks for your assistance
Gabriel

**Comment by Gay-MC** [comment]
I have now got this error on a number of combinations, including partitions = "none" and partitions = "user".

I have emailed an RDATA file that I hope will be sufficient to recreate this error.

**Comment by jamiemkass** [comment]
@Gay-MC, I'm not sure the Rdata file will be much help because it's the particular configuration on your machine that's causing dismo to use the old Maxent version. Have you tried starting a new session after you confirm that 3.4.4 is in the dismo/java folder? Perhaps you could also confirm the version via dismo itself? ENMeval is just calling dismo, so this is an issue with which version of Maxent dismo uses.

**Comment by Gay-MC** [comment]
Yes, I have done those checks. Would an RDS file be better?

**Comment by jamiemkass** [comment]
What I meant to say was that ENMeval just calls Maxent through dismo, so the version of Maxent that dismo uses is the one that pops up when you run `ENMevaluate()`. Thus, you need to investigate why dismo is reading the wrong version of Maxent.

**Comment by Gay-MC** [comment]
Thanks
I will look into this.

**Comment by Gay-MC** [comment]
Thanks Jamie. The problem was fixed by deleting all versions of dismo and Maxent from my computer (even the stand-alone version) and reinstalling dismo as you suggested.

At the same time, I also replaced  
  fc = "LQ", RMvalues=2.5
with
  tune.args = list(rm = 1, fc = "LQ") 
as you suggested for fixing the null model bug.

Many thanks for this advice.
