### ISSUE TITLE
removeDuplicates default

### ISSUE THREAD

**Issue by mclinx013** [jamiemkass/ENMeval#123]
Hello, I am trying to run the enmEvaluate function but with the added argument that I want maxent.jar to run without removing data points that share the same location. After reading the function documentation, I've tried assigning other.args the value of "removeDuplicates=FALSE" and then passing that via the other.settings argument for the function. However when I do this I get the error: "Error: $ operator is invalid for atomic vectors" - I am sure I'm just missing something obvious here and would appreciate whatever guidance you might be able to offer! Thanking you in advance!

FYI this is what I've been doing:

other.args <- "removeDuplicates=FALSE"
gat_mx <- ENMevaluate(occs = gat, envs = env_layers, bg = bg, 
                    algorithm = 'maxent.jar', partitions = 'block', other.settings = other.args,
                    tune.args = list(fc = c("L","LQ","LQH","H"), rm = 1:5))

**Comment by jamiemkass** [comment]
So sorry I'm getting to this late. I realized now that this is not explained in the current documentation, so I will add it for the next version. You need to wrap your argument in a list for input with the name other.args, like this:
`other.args <- list(other.args = "removeDuplicates=FALSE")`

Please let me know if you have any issues with this, but it should work.

**Comment by jamiemkass** [comment]
@mclinx013, thanks for your patience. I found a bug in the code that was not populating the default elements in the other.settings list when the user specified other.settings when running ENMevaluate(). I fixed this, then bundled it with some other fixes that I was accumulating and pushed a new version 2.0.4 to the master branch. Please install this version and let me know if you have any more issues.

**Comment by mclinx013** [comment]
Ah wonderful thank you very much! I managed to download it via the clampStuff branch as the master branch only loaded 2.0.3.... but it's now up and working so thank you again for all your help!

**Comment by jamiemkass** [comment]
Great! Very glad it works now, and thanks for helping me identify this bug. Funny though -- the master branch should be 2.0.4 now.
