### ISSUE TITLE
error including categorical data

### ISSUE THREAD

**Issue by Cookiegai** [jamiemkass/ENMeval#127]
Hello, I am using the R package ENMeval to determine the appropriate settings that I would use in maxent for my study. Upon trying to use the code whilst following Mr. Banta's tutorial. I keep getting the same error when I try to run input that I've typed.

Here is the code:
enmeval_results <- ENMevaluate(occ, env, bg = NULL, tune.args = list(fc = c("L","LQ","H", "LQH", "LQHP", "LQHPT"), rm = 1:5), partitions = "jackknife", algorithm = "maxnet", categoricals = c("landcoverb", "hwsdcutb"))

After running the code, the usual steps follow until this shows up and terminates the process:

* Assigning variable landcoverb to categorical ...
* Assigning variable hwsdcutb to categorical ...
Error in `[.data.frame`(d, , categoricals[i]) : 
  undefined columns selected
  
  Any insight would be appreciated, Thanks
  
  PS. I've tried running the command without the categorical data and it works just fine, hence why I assumed I'm dealing with an issue associated with my input with categorical data.

**Comment by jamiemkass** [comment]
This sounds like an issue that should be solved by installing the latest version on Github.

`remotes::install_github("ENMeval/jamiemkass")`

Please let me know if this fixes it.

Jamie

**Comment by Cookiegai** [comment]
Thank you for responding with my inquiry

I was about to ask about the code you gave but it turns out it should be "jamiemkass/ENMeval" (which finally installed the latest thingy)

However, a new error arose, I am not sure what went wrong this time, here is the error code that I got after trying to run the code (it stopped at 3%): 

in (function (p, data, f = maxnet.formula(p, data), regmult = 1,  : 
  Error: glmnet failed to complete regularization path.  Model may be infeasible.
In addition: Warning messages:
1: In .couldBeLonLat(x, warnings = warnings) :
  CRS is NA. Assuming it is longitude/latitude
2: from glmnet C++ code (error code -174); Convergence for 174th lambda value not reached after maxit=100000 iterations; solutions for larger lambdas returned

I am assuming that it is infeasible due to the high correlations between the layers as I have not yet removed them from the matrix (I thought of removing said layers after running maxent with the appropriate parameters and base my selection according the jackknife result) or could it be the layers itself being janky (but I have already made sure that they have the same resolution and extent)

It is my first time conducting an SDM study, hence I am unfamiliar with this approach. I truly appreciate the help you provide. 

PS. I am still using the same code from earlier (maybe there's something wrong with my input I am not sure as well :< )

**Comment by jamiemkass** [comment]
I've seen this error arise for very complex models with hinge features and large input datasets. Try the model again without hinge features, else use maxent.jar which usually can fit such complex models without erroring (glmnet sometimes has issues).

**Comment by Cookiegai** [comment]
I've tried running the code again with the hinge features removed by just using (I hope I did it right):

tune.args = list(fc = c("L","LQ") 

instead of 

tune.args = list(fc = c("L","LQ","H", "LQH", "LQHP", "LQHPT")

Here is the error that I got after running the code:

* Found 20585 raster cells that were NA for one or more, but not all, predictor variables. Converting these cells to NA for all predictor variables.
* Randomly sampling 10000 background points ...
* Assigning variable landcoverb to categorical ...
* Assigning variable hwsdbscutb to categorical ...
Error in `[.data.frame`(d, , categoricals[i]) : 
  undefined columns selected
In addition: Warning message:
In .couldBeLonLat(x, warnings = warnings) :
  CRS is NA. Assuming it is longitude/latitude

What did you mean by using maxent.jar, could you please elaborate more about it (I do know how to operate maxent but I'm assuming you're talking about something else)

Do I have to do clamping? I read somewhere that categorical data needs to be clamped or something. Mr. Banta's tutorial did not really discuss how to do that.

**Comment by jamiemkass** [comment]
You have at least one predictor variable that has NA for grid cells that have a value for 20,585 cells of the other rasters. Can you check your raster data in a GIS (ArcGIS, QGIS)? ENMeval is making all these cells NA for all rasters, and you are likely losing lots of data. This might be causing the errors you see.

Clamping is recommended to prevent free extrapolation when transferring your model to other places or times. It converts all new values to the most extreme value in the training data before making predictions. Clamping does not affect categorical variables at all, only continuous ones.

**Comment by jamiemkass** [comment]
Try running `raster::extract(envs, occs)` on your data, because that's what ENMeval uses to find occurrences with NA for one or more env predictor variables. You can do `cbind(occs, extract = z)` if z is the extract output for a particular variable, then plot the occurrences with color set to "extract" to see which points were NA.

**Comment by Cookiegai** [comment]
Greetings, I would like to apologize that I took awhile to reply due to other academic responsibilities. We were able to push through with ENMEval by removing the categorical layers (we assumed it's was too complicated for R to include in the process said layer). We found an alternative categorical layer and it runs ENMEval just find however when viewing the results all the delta.AlCc are NA as seen in the image below.

![image](https://user-images.githubusercontent.com/109427997/183611953-d8642666-ba2a-4a0e-bef2-8c6d92bf2152.png)

I also assume that the problem is related with the error code that I received after running ENMEval.

Warning: model fc.L_rm.1 has more non-zero coefficients (ncoef) than occurrence records for training, so AIC cannot be calculated.
Warning: model fc.LQ_rm.1 has more non-zero coefficients (ncoef) than occurrence records for training, so AIC cannot be calculated.
Warning: model fc.H_rm.1 has more non-zero coefficients (ncoef) than occurrence records for training, so AIC cannot be calculated. (multiple instances of this error can be seen on the console but did not want to make this a wall of text so I just placed a few)

Also, I tried running raster: : extract(envs, occs) but I was not able to interpret it properly.

**Comment by Cookiegai** [comment]
So we sorta figured out the reason for the NA results for delta.AiCc, we realized it was related with the occurrence data (not entirely sure, but had another species to compare outcome). I know it's not related with the current problem with categorical data but would want to ask if there is a way to adjust the intervals for RM? We were thinking of using 0.5 intervals rather than 1 (so results would be like 0.5, 1.0, 1.5, 2.0....). I've tried looking into the CRAN manual thingy and I did not see a way to alter the interval.

**Comment by jamiemkass** [comment]
You are getting the AIC error because your model has more non-zero coefficients than occurrence records. In other words, your sample size is lower than the number of model coefficients, which goes against the assumptions underlying information criteria like AIC. This can easily happen when you include hinge or product features because you can get lots of coefficients. This doesn't mean the model is "bad", just that it's likely very complex.

As for intervals of rm, you can use `tune.args = list(rm = seq(1, 5, 0.5))` or some other variation to change the intervals.

**Comment by Cookiegai** [comment]
I tried running the code you provided and it was a tad bit confusing to use but was able to perform ENMEval, kinda confused with the results, as it did not give me the entire extent of my indicated scope (0.5 - 5, in 0.5 intervals), is this some kind of feature when you use "rm = seq(1...)" instead of "rm = 1:5" that it already excludes results with NA?

Thank you also for confirming my assumptions with regards to interpreting the result.

**Comment by jamiemkass** [comment]
The code I provided is the specification of the argument `tune.args` for running `ENMevaluate()`. Please see `?ENMevaluate` and the vignette for examples. If it's unclear how to use `seq()`, you can experiment with it in the console, but the code I specified should return a vector of numbers 1, 1.5, 2,... to 5. Not sure why you did not see all the rm values you specified in your results though. If you give me more details on what the results look like I can try to diagnose.

**Comment by jamiemkass** [comment]
Closing this for now, but please let me know if this issue persists.
