### ISSUE TITLE
Error after reinstalling ENMeval 2.0.3

### ISSUE THREAD

**Issue by cesmarc** [jamiemkass/ENMeval#129]
Hello,
I am having problems after reinstalling ENMeval 2.0. My scripts that used to work normally started to show the following error:
Error in data.frame(auc.train = auc.train, cbi.train = cbi.train) : 
  arguments imply differing number of rows: 1, 0
In addition: Warning message:
replacing previous import ‘grid::arrow’ by ‘terra::arrow’ when loading ‘rasterVis’ 
Is there a solution to this?
Thanks!

**Comment by jamiemkass** [comment]
Yes, this should be fixed after you update the ecospat package. ENMeval 2.0.3 addresses a change to param names for some ecospat functions.

**Comment by cesmarc** [comment]
It worked! Thank you.
