### ISSUE TITLE
Problem with variable importance

### ISSUE THREAD

**Issue by KellumTJ** [jamiemkass/ENMeval#130]
Howdy!

I am currently trying to calculate the variable importance for MaxEnt models generated by ENMevaluate but am running into problems. Here is the code I used to generate my models:

`mod_e.mx.1 <- ENMevaluate(occs = mod_occs, envs = curr_envs, bg = mod_bg, algorithm = 'maxnet',
                      partitions = 'checkerboard1', tune.args = list(fc = fc, rm = rm))
`
I then tried to determine the variable importance for each of the generated models using the following code:

`mod_e.mx.1@variable.importance`

However, this returned "NULL" for each of the generated models. I don't understand why it is returning "NULL"; did I set up my ENMevaluate run in a way that it would not return this information?

I also tried to use the "eval.variable.importance" function both on the entire ENMevaluate object (#Attempt 1#) and on the model with the lowest AICc, denoted by "mod_aicmod" (#Attempt 2#):

`#Attempt 1#
eval.variable.importance(mod_e.mx.1)
#Attempt 2#
eval.variable.importance(mod_e.mx.1@models[[mod_aicmod]])`

Each of these attempts gave me the same error message: "Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘eval.variable.importance’ for signature ‘"maxnet"’." 

I'm fairly certain this is user error so I would greatly appreciate any guidance on this topic--I would like to calculate both the variable percent contribution and the permutation importance. Thank you in advance for your help!

Sincerely,
Kellum

**Comment by KellumTJ** [comment]
I figured out that if I run the ENMevaluate with algorithm = "maxent.jar" instead of "maxnet" I am able to get the information I need. Solved!

**Comment by jamiemkass** [comment]
So sorry for the delay in response. The package maxnet does not have a native implementation of permutation importance like maxent.jar does, so ENMeval does not report it for maxnet models. There are other packages that implement this generically for models, so you could use these tools to calculate permutation importance for maxnet models too.

**Comment by KellumTJ** [comment]
Many thanks!
