### ISSUE TITLE
When using maxnet, how to turn addsamplestobackground = F

### ISSUE THREAD

**Issue by silasprincipe** [jamiemkass/ENMeval#136]
Hi,

I'm using ENMeval with `maxnet`, but I want to turn off the option of adding the samples to the background. This is because I want to use maxent under a Point Process framework (https://doi.org/10.1111/2041-210X.12352).

I tried adding this option in the `other.setings` argument, as follow, but an error was produced (`Error in (function (p, data, f = maxnet.formula(p, data), regmult = 1,  :  formal argument "addsamplestobackground" matched by multiple actual arguments`):

```
other.settings = list(other.args = list(addsamplestobackground = F))
```

Sorry if I'm missing something very obvious. I appreciate any help you can give!

**Comment by jamiemkass** [comment]
The argument `other.settings` is hard-coded as TRUE in the ENMdetails object that specifies maxnet implementation (in R/enm.maxent.R). You can always change the internal functions though like this:

`enm.maxnet@args <- myFunction`

where myFunction is an edited version of `maxent.args` in R/enm.maxent.R. Then when you run ENMevaluate, it should use your new args function to specify the arguments in `maxnet()`. Perhaps in the next update I can just add the argument `addsamplestobackground` to the `other.settings` list so this will be easier.

Please confirm that this works!

Jamie

**Comment by silasprincipe** [comment]
Hi Jamie, thanks for the answer (and sorry for taking so long to answer).

I tested your suggestion and it seems to work! Just to be sure, I tested creating another ENMdetails object and calling this directly from the ENMevaluate function:

```
enm.new <- enm.maxnet

enm.new@name <- "new"

enm.new@args <- function(occs.z, bg.z, tune.tbl.i, other.settings) {
  out <- list()
  out$data <- rbind(occs.z, bg.z)
  out$p <- c(rep(1, nrow(occs.z)), rep(0, nrow(bg.z)))
  out$f <- maxnet::maxnet.formula(out$p, out$data, classes = tolower(tune.tbl.i$fc))
  out$regmult <- tune.tbl.i$rm
  # some models fail to converge if this parameter is not set to TRUE
  # usually the case with sparse datasets
  out$addsamplestobackground <- FALSE
  out <- c(out, other.settings$other.args)
  return(out)
}

e.mx.l2 <- ENMevaluate(occs = pts, envs = env, bg = quad, partitions = "randomkfold",
                      algorithm = "new",
                       tune.args = list(fc = "L", rm = 1:2),
                      user.enm = enm.new)
```

But of course, adding "addsamplestobackground" to the `other.settings` will be nice.

Thanks,

Silas

**Comment by jamiemkass** [comment]
Great to know it worked! I will leave this open now to make sure I make this change in the next update.

**Comment by jamiemkass** [comment]
Just added this functionality to v2.0.5. Check it out! See the new documentation on addsamplestobackground in `?ENMevaluate`.
