### ISSUE TITLE
Jackknife variable importance

### ISSUE THREAD

**Issue by mclinx013** [jamiemkass/ENMeval#139]
Hi,

Is it possible to have the jackknife test wrapped into the ENMevaluate call? I've tried running it as part of the other args but it doesn't seem to work and instead creates a new folder called "jackknife=TRUE" in my working directory... Not sure whether I'm just calling the other.args incorrectly?

other.args <- list(other.args = ("jackknife=TRUE"))

Any guidance is truly appreciated!

**Comment by jamiemkass** [comment]
Sorry, do you mean the jackknife test of variable importance that maxent.jar does? You should be modifying the `other.settings` argument in the `ENMevaluate()` call, like this:

`other.settings = list(other.args = "jackknife=TRUE")`

Can you confirm that this gives you the same result? Not sure why a folder would be created.

**Comment by jamiemkass** [comment]
I figured out what was wrong and fixed it in v2.0.5. Please see the new example in `?ENMevaluate` that saves the jackknife plots to a directory specified by the user.

Install the new version with this:
`remotes::install_github("jamiemkass/ENMeval@v205_draft")`

**Comment by mclinx013** [comment]
Hello @jamiemkass - I've now downloaded the latest version (v2.0.5) but am now running into Java issues. This is definitely a result of downloading the latest version as I was running rJava just prior to the update. I am able to load rJava via the library function & can also run .jinit() without issue - however when I run ENMevaluate, I now get the following error: 

Error in enm@msgs(tune.args, other.settings) : 
  java.lang.ClassNotFoundException

Any idea what may have happened? Thanks!
