### ISSUE TITLE
Running ENMeval got stuck at 0% for hours

### ISSUE THREAD

**Issue by adwiputra** [jamiemkass/ENMeval#144]
Hi, I was running ENMevaluate with "maxent.jar" on a machine with 128 GB RAM and not long after, the memory used became 83 GB. However, the progress bar didn't increase from 0% for an hour or so, and I received several warning messages about low memory from Windows. Another thing that made me wonder was the low CPU usage. Is there a way to check if maxent.jar is actually running in the background?

Thank you so much for such a useful package!

**Comment by jamiemkass** [comment]
Thanks for using the package. This may happen if you are inputting very large rasters (like global ones at high resolution), so a way around this is to mask the rasters by your study extent for the species (i.e., the area you will sample background from, which defines the area accessible to the species). You can also try running maxent.jar by itself to test, but the Java implementation is typically quicker than the R one (maxnet).

**Comment by adwiputra** [comment]
Thanks for your speedy response!

The computer crashed after leaving the process running despite the 0% stuck progress bar, so something might be running in the background.
When I tried to move the processing to a more powerful computer, it wasn't stuck as before, but instead, it gave out the Heap size errors. This is a different issue from what this post was originally about so I wouldn't go into too much detail here.

**Comment by jamiemkass** [comment]
Did you try my recommendation for reducing the raster sizes?

**Comment by adwiputra** [comment]
> Did you try my recommendation for reducing the raster sizes?

Hi, sorry it took me a while to get back to this. Unfortunately, this potential solution is not suitable for my case because I already use a relatively coarse resolution of 1 sq km. Instead, I am now trying to run Maxent in a non-predictive mode, i.e. not providing an env argument with the raster stack.
However, when I did this, the process returned an "undefined column selected" error. Related to this, I read this post https://groups.google.com/g/maxent/c/vAB5G3Eo1ho and now am running the code with categorical variables argument explicitly specified. Crossing my fingers..
