### ISSUE TITLE
Task failed : "Unspecified column selected" 

### ISSUE THREAD

**Issue by adwiputra** [jamiemkass/ENMeval#146]
Hi, I ran into a problem when running ENMevaluate in parallel mode with categorical predictors. The process always failed with the "Unspecified column selected" error. Based on what I read on the web and trials and errors, I figured out that the error only happens when I included my categorical predictors. I also did a trial run at the same resolution using the standalone maxent.jar and it ran without error.  Has there been a potential workaround to this?

Thanks!

**Comment by jamiemkass** [comment]
Just checking, but have you updated to the latest version? There was an issue with categorical predictors that I fixed in the last version.

**Comment by adwiputra** [comment]
Yes, I encountered the error in the latest cran version 2.0.4.

**Comment by jamiemkass** [comment]
Thanks for the info. And does this also happen when you are not running in parallel?

**Comment by adwiputra** [comment]
> Thanks for the info. And does this also happen when you are not running in parallel?

Unfortunately, I cannot confirm this because not running in parallel would take very long to get the process to the point where the error occurred. However, let me know if there is actually a way I can test this. Thanks so much!

**Comment by jamiemkass** [comment]
I wonder if you resolved this issue or not. One way to test would be to reduce your dataset size considerably but keep the predictors the same.

**Comment by jamiemkass** [comment]
Closing this for now, but please let me know if this issue persists.
