### ISSUE TITLE
Cannot run the 3.4.4 version of MAXENT

### ISSUE THREAD

**Issue by LorenzoBernicchi** [jamiemkass/ENMeval#147]
Hello everyone, 

I am trying to run an ENM using the `ENMevaluate` function. I had the `maxent.jar` file on my PC, the version 3.4.4.
However, when I run the function it tells me that it is running the `maxent.jar v3.4.3` from the `dismo` package v1.3.14
I would like to know how can I make the package able to run the latest version of MAXENT.

Thank you in advance, I wish you a great day!

**Comment by jamiemkass** [comment]
Have you put the new `maxent. jar` file in the java folder of dismo and replaced the old one? Check `?dismo::maxent` for the location.

**Comment by LorenzoBernicchi** [comment]
I just checked and that function tells me I am using the older version of `maxent`. May I ask you how to solve this?

Moreover, I have another question: I built a model and I would like to transform it into a binary presence/absence layer using the maximizing sensitivity plus specificity. However, I cannot find these values in the resulting object nor I can find any functions to do so. May I ask you for help?

**Comment by jamiemkass** [comment]
The documentation for the `dismo::maxent` function tells you where to find the `java` folder for the dismo package. You need to manually drop your new `maxent.jar` file there and replace the existing one.

Regarding max spec sens, it is really most appropriate for presence-absence models, not presence-background like Maxent, as specificity (true negative rate) is not relevant for presence-background data. I recommend using 10 percentile suitability, or the suitability score at the bottom 10 percentile. This ignores the lowest suitability scores and uses a relatively conservative threshold, plus it's data-driven and does not rely on specificity. There's an internal function to calculate that in ENMeval, or you can just get the predicted values for all your occurrence records and find the bottom 10 percentile value.

**Comment by LorenzoBernicchi** [comment]
Thank you so much for your answer @jamiemkass !!

Regarding the transformation into binary maps, do you mean the function `calc.10p.trainThresh()`? I tried to use it but it tells me 
```r
could not find function "calc.10p.trainThresh
``` 
I don't know if I am doing something wrong, but with this type of error this should be an issue regarding the function within the package.

**Comment by jamiemkass** [comment]
That's because the function is not exported (there is no header with @export), so when you load the package with `library(ENMeval)`, it is not in the environment. It is meant to be an internal function. However, you can still run the function definition and use it in a session.

`calc.10p.trainThresh <- function(pred.train) {
  n <- length(pred.train)
  if(n < 10) {
    pct90.train <- floor(n * 0.9)
  }else{
    pct90.train <- ceiling(n * 0.9)
  }
  pct10.train.thr <- rev(sort(pred.train))[pct90.train]
  return(pct10.train.thr)
}
`

After running this, you should be able to use it. You'll need to give it a vector of predicted values for the training points (use `raster::extract()`).

**Comment by LorenzoBernicchi** [comment]
Ah okay, perfect! I missed the part about exporting the functions! 
Thank you again so much, have a nice day!
