### ISSUE TITLE
Missing newline in 'show' method for  ENMevaluation objects

### ISSUE THREAD

**Issue by plantarum** [jamiemkass/ENMeval#152]
I admit this is a trivial issue!

When printing an ENMevaluation object, the final line doesn't have a new line. That leaves the prompt at the end of that line, and makes my obsessive-compulsive eyes twitch.

https://github.com/jamiemkass/ENMeval/blob/199bf0181716b25ea5033be16ed8c6efadcfbd95/R/classes.R#L300

Adding a `\n` should resolve this:

```R
cat("Refer to ?ENMevaluation for information on slots.\n", sep = "") 
```

Thanks for your work, this package is invaluable!

**Comment by jamiemkass** [comment]
Thanks, @plantarum! I am obsessive-compulsive too, so I appreciate your obsessive comment. I added `\n` to all show methods for classes in v2.0.5.
