### ISSUE TITLE
Error on ENMnulls when parallel = TRUE

### ISSUE THREAD

**Issue by mauriciovancine** [jamiemkass/ENMeval#154]
Dear @jamiemkass, firstly, thank you for maintaining the ENMeval package.

I would like to report a bug with the ENMnulls function when using the parallel=TRUE argument for parallelType="doParallel" and "doSNOW".

The error was:

```
Building and evaluating null ENMs with 100 iterations...
Of 12 total cores using 10...
Running in parallel using doSNOW...
  |================================================================================================================================| 100%
  
  Error in { : task 2 failed - "object 'e' not found"
 ```
 
 Thanks again.

**Comment by jamiemkass** [comment]
@mauriciovancine, thank you so much for alerting me to this error, and I apologize for the late response. I was making the final touches to 2.0.5, and managed to fix this too. I guess `foreach` updated and might work slightly differently than before, but adding a `.export = c("e")` to the parameters of `foreach()` made this work. I now added a new unit test to make sure parallel implementations also work for null modeling. Version 2.0.5 should be up on CRAN soon.

Thanks again,

Jamie

**Comment by mauriciovancine** [comment]
@jamiemkass, thank you for correcting this error.

I will test and report if there were any errors.

Best,

Maurício
