### ISSUE TITLE
Extracting data for response curves

### ISSUE THREAD

**Issue by elefal** [jamiemkass/ENMeval#157]
Is there anyway to extract the data used to plot the response curves? I'd like to use ggplot2 to customize and edit aesthetics, but previous answers to this question are from 2021 and no longer work: 

https://github.com/jamiemkass/ENMeval/issues/104
https://groups.google.com/g/maxent/c/LjyYh0uEcMk

> plot(p.mod@models[[1]], type="cloglog") works fine.

Using dismo::response(p.mod@models[[1]]) returns 
Error in .local(x, ...) : 
  The model object does not seem to have the data used to fit it. Provide these with a "data= " argument

Thanks!

**Comment by elefal** [comment]
I failed to mention in the first post that I was using the "maxnet" algorithm.
I found a workaround after several hours of digging. I'm pasting it here for future reference if anyone is looking to do the same thing. "X5kmbio2" is the name of one of my environmental layers in the RasterStack.

```r
mod<-p.mod@models[[1]]
respcurve<-maxnet::response.plot(mod, "X5kmbio2", type="cloglog",
                              mm=mod$samplemeans, min=mod$varmin["X5kmbio2"], 
                              max=mod$varmax["X5kmbio2"],
                              levels=unlist(mod$levels["X5kmbio2"]),plot=F)
```

**Comment by jamiemkass** [comment]
Thanks very much for this, @elefal. Perhaps we should put this in the documentation examples.

**Comment by jamiemkass** [comment]
Added this to the documentation for v2.0.5: f52fdb5ce9dc89de5613735862cc2575deb1f21f
