### ISSUE TITLE
Add option for bias file

### ISSUE THREAD

**Issue by bobmuscarella** [jamiemkass/ENMeval#26]
I might be wrong but it seems that the "simple" options here don't seem to work...

At first I thought one possibility would be to use a user-defined bias layer for generating the background points.  For `ENMeval`, maybe it could happen by editing the background generation in the `ENMevaluate` function to something like this:

``` r, eval=F
if (is.null(bg.coords)) {
  if (!is.null(biaslayer)) {
    if(n.bg > ncell(bias)) {
      message("Warning: n.bg > ncell(bias). n.bg changed to ncell of the bias layer.")
      n.bg <- ncell(bias)
    }
  bg.coords <- randomPoints(biaslayer, n = n.bg, prob = T)
  } else {
  bg.coords <- randomPoints(env[[1]], n = n.bg)
  }
}
```

However, in a little bit of testing, it seems that using the `prob` argument in `randomPoints` can lead to problems if the number of points (n.bg) > 1/3 the number of grid cells.  Try this:

``` r, eval=F
bias <- raster(matrix(runif(100), 10, 10))
randomPoints (bias, 34, prob=T)
randomPoints (bias, 33, prob=T)
```

Perhaps this calls for contacting Robert Hijmans figure out the root of the problem in the `randomPoints` function?

**Comment by bobmuscarella** [comment]
***Based on another email request about this from Juan Parra, I wrote:***

Hi Juan -

Jamie Kass and I have been talking about adding an option for the bias layer in ENMeval but it is not currently implemented.  We think the main complication is that ENMevaluate uses the SWD format when doing the maxent call (this is so we can use the same background points for each run and thus have comparable evaluation statistics).  But maxent doesn't support a bias file when using the SWD format.

We thought a reasonable workaround might be that a user defined bias file could be used to weight the selection of background points, which are then passed to the ENMevaluate function.  I'm not sure of the exact ways this differs from giving maxent a bias file but I think it would be a decent option.  Check out the code I pasted below for a simple way to do this.
...

```{r}
########################################################################
### Simulated data environmental covariates
set.seed(1)
r1 <- raster(matrix(nrow=50, ncol=50, data=runif(10000, 0, 25)))
r2 <- raster(matrix(nrow=50, ncol=50, data=rep(1:100, each=100), byrow=TRUE))
r3 <- raster(matrix(nrow=50, ncol=50, data=c(rep(1,1000),rep(2,500)),byrow=TRUE))
env <- stack(r1,r2,r3)
biasfile <- raster(matrix(nrow=50, ncol=50, data=rep(seq(0,1,length.out=500), each=100)))

### Simulate occurrence localities
nocc <- 50
x <- (rpois(nocc, 2) + abs(rnorm(nocc)))/11
y <- runif(nocc, 0, .99)
occ <- cbind(x,y)

### Select background points using bias file
bg <- xyFromCell(biasfile, sample(ncell(biasfile), 500, prob=values(biasfile)))

### Look at the bg and occ records with respect to the bias file
plot(biasfile)
points(bg)
points(occ, pch=16)

### Pass the background coordinates onward...
res <- ENMevaluate(occ, env, bg.coords=bg, ...)
```

**Comment by bobmuscarella** [comment]
***I then asked Cory Merow about this and here is his useful reply:***

On Tue, Dec 6, 2016 at 7:50 PM, Cory <cory.merow@gmail.com> wrote:
Hey Bob,
I haven't actually tried it but it sounds like you're proposing what I'd do : generate the swd file by sampling points with probabilities equal to those in the bias file. Then the catch is that to predict you need to factor the bias back out of the prediction by dividing the raw value by the bias value in the respective cell. And then normalize the whole raster to have proper raw output. Hope that helps, and let me know if you have any issues, as I haven't actually tried it.
Cory

**Comment by ndimhypervol** [comment]
I like this conversation, but I am not clear on Cory's method. If you sample background pts with the bias as probabilities per cell, then doesn't that account for the bias (at least partially) in the model? Thus, any predictions you make shouldn't need any transformations, as the bias was accounted for. Unless I'm missing something.

**Comment by bobmuscarella** [comment]
Try this simulation.  It selects biased background points based on a bias raster.  Then the 'untransformed' prediction is compared to the prediction after factoring out bias like Cory suggested.

```{r}
### Simulated data environmental covariates
set.seed(1)
r1 <- raster(matrix(nrow=50, ncol=50, data=runif(10000, 0, 25)))
r2 <- raster(matrix(nrow=50, ncol=50, data=rep(1:100, each=100), byrow=TRUE))
r3 <- raster(matrix(nrow=50, ncol=50, data=c(rep(1,1000),rep(2,500)),byrow=TRUE))
env <- stack(r1,r2,r3)

### Simulate bias file
bias <- raster(matrix(nrow=50, ncol=50, data=rep(seq(10,80,length.out=25), each=100)))

### Simulate occurrence localities
nocc <- 50
x <- (rpois(nocc, 2) + abs(rnorm(nocc)))/11
y <- runif(nocc, 0, .99)
occ <- cbind(x,y)

### Select biased background
n.bg <- 500 # number of background points
biased.bg <- xyFromCell(bias, sample(ncell(bias), n.bg, prob=values(bias)))
plot(bias)
points(biased.bg)

### Run Maxent
x <- as.data.frame(rbind(extract(env, occ), extract(env, biased.bg)))
p <- c(rep(1, nrow(occ)), rep(0, nrow(biased.bg)))
m <- maxent(x, p)

### Predict model
pred <- predict(m, env, args='outputformat=raw')
plot(pred)
points(occ)

### Factor out bias as according to Cory's suggestion
pred.corrected <- pred/bias
plot(pred.corrected)
points(occ)
```

**Comment by cd-barratt** [comment]
Hi Bob, 

I'm trying to follow this last item you pasted from Cory's answer to generate background points from a bias file to feed into ENMeval. However I'm running into difficulty when I read in my own bias file rather than use the simulated one, could you help me troubleshoot this? When I run xyFromCell I'm receiving an error "Error in sample.int(x, size, replace, prob) : NA in probability vector". I first thought this was to do with NAs in my raster, but I have tried removing these and also tried with other files (tif, asc) and I repeatedly run into the same problem. Any idea where I'm going wrong here? I've attached my bias file as a zip.

Cheers,
Chris

###read in bias file
bias <- raster("bias_file.tif")

### Select biased background
n.bg <- 500 # number of background points
biased.bg <- xyFromCell(bias, sample(ncell(bias), n.bg, prob=values(bias)))
plot(bias)
points(biased.bg)

[bias_file.tif.zip](https://github.com/bobmuscarella/ENMeval/files/2286287/bias_file.tif.zip)

**Comment by bobmuscarella** [comment]
Hi Chris -

It seems to be because you have NA's in your bias file and you cannot have
NA's in the 'prob' argument of the 'sample' function (they get included
there when you use 'values(bias)').  The simulated version doesn't have
NA's because it is a square raster but I guess non-rectangular rasters will
always have this issue.  I'm not sure how you removed the NA's before but
try this:


n.bg <- 500 # number of background points

# Set the probability of all cells with NA to zero
values(bias)[is.na(values(bias))] <- 0

biased.bg <- xyFromCell(bias, sample(ncell(bias), n.bg, prob=values(bias)))

# I'm not sure why you have such a large extent on your raster when the
area with data is so small.  You might want to crop it?
plot(bias, xlim=c(34,44), ylim=c(-12,2))
points(biased.bg)

**Comment by cd-barratt** [comment]
Thanks Bob - that now works a treat. FYI I removed the NAs in a text editor... wasn't a great idea... cheers for fixing my problem!

**Comment by andliszmmu** [comment]
I try to play with composition of background points as well as other parameters. So I have several questions on this topic.
First of all, there are some unclear points in the help. We have an n.bg option as "The number of random background localities to draw from the study extent". It looks like this option works only if bg.coords are not set. Is it so?
Second, I use 
ENMevaluate(csv.spp@coords, env.stack, bg.coords = bg, algorithm = 'maxnet', fc = c("L", "LQ", "H", "LQH", "LQHP"), RMvalues = c(0.25, 0.5, 0.75, 1, 2, 3, 4, 5), method = 'block', n.bg = 10000, parallel = T, numCores = 2, rasterPreds = F)
Do I understand correctly if: with such settings the model is built on the basis of bg (as background points) only, the model is projected on env.stack after that (if rasterPreds = T for example)? The 'block' method of evaluation is used - spatially independent blocks analysed as test data. These options are not difficult to understand - the question is, do I understand correctly, how all these options work together?
The third question is about Cory's comment )) I don't understand it, frankly speaking ) Do I need some correction every time I use some restrictions on background points sample? Here is my code
base_dir         <- "some_path"
csv.file          <- "neomys.csv"
bias.file         <- "bias.csv" #points for background sample - well studied locations
env.file         <- list.files(path="some_path",pattern = ".asc$",full.names = T,include.dirs = F)
prj                 <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
buffer.val       <- c(5000, 10000, 25000, 50000)
max.bckg         <- 10000

csv.dat          <- read.csv(paste(base_dir, csv.file, sep=""))
csv.spp          <- SpatialPoints(cbind(csv.dat[,2],csv.dat[,3]),prj)
bias.dat         <- read.csv(paste(base_dir, bias.file, sep=""))
bias.spp         <- SpatialPoints(cbind(bias.dat[,2],bias.dat[,3]),prj)

time_start       <- Sys.time()

env.stack        <- lapply(env.file,raster,crs=prj,NODATA="-9999") 
env.stack        <- stack(env.stack)

for (i in 1:length(buffer.val))
  {
bias.buf         <- buffer(bias.spp, width=buffer.val[i])
bg                <- as.data.frame(extract(env.stack[[1]], bias.buf, cellnumbers = T, na.rm=T))
bg                <- bg[!is.na(bg$value),]
bg.num           <- length(bg[,1])
if (bg.num > max.bckg) bg        <- bg[sample(nrow(bg), max.bckg),]
bg                 <- as.data.frame(xyFromCell(env.stack[[1]], bg$cell))
mod              <- ENMevaluate(csv.spp@coords, env.stack, bg.coords = bg, algorithm = 'maxnet', fc = c("L", "LQ", "H", "LQH", "LQHP"), RMvalues = c(0.25, 0.5, 0.75, 1, 2, 3, 4, 5), method = 'block', n.bg = 10000, parallel = T, numCores = 2, rasterPreds = F)
for (k in 1:length(mod@models))
{
  model.ras       <- maxnet.predictRaster(mod@models[[k]], env.stack, clamp=T, type='link')
  aic                  <- calc.aicc(length(mod@models[[k]]$lambda), csv.spp@coords, model.ras)
  mod@results[k,13] <- aic[1]
}
mod@results[,14]  <- mod@results[,13] - min(mod@results[,13])
model.ras       <- maxnet.predictRaster(mod@models[[which(mod@results$delta.AICc == 0)[1]]], env.stack, clamp=T, type='cloglog')
}
Thank you

**Comment by ndimhypervol** [comment]
To answer your questions:
1) Yes, n.bg only works if bg.coords is not set.
2) Your description seems okay. Do you have any specific questions about the internal workflow in ENMeval?
3) I am still not too sure about Cory's correction to the raw output. From what I commonly see done, you sample background points over a probabilistic raster reflecting the sampling bias (as in Bob's example). I usually use cloglog transformation, so I don't make any corrections to raw outputs. Not sure you need to, but I guess it might be worth reaching out to Cory again.

**Comment by andliszmmu** [comment]
Thank you very much! It really helps

**Comment by andliszmmu** [comment]
Dear Jamie, I lived a little with my code and I have some questions now! ))
It is one or two related questions indeed. But not short, sorry. Well, if I use ENMevaluate with rasterPreds = F option, I get a stack of nice rasters that are a 'raw output' of maxnet. But this option (rasterPreds = F) kill all my resources, mainly memory, not only time. I tried to predict rasters after ENMevaluate execution, but... I cannot find, how to predict raw output. There are cloglog etc, including 'link' (something odd that gives me negative scale sometimes) but not raw.
The second part of the question is about thresholds. Well, it is a bad thing at all, but useful in some cases. This question has two parts. a) mod@results contains some threshold values. But what is the scale? It is obviously not in raw scale. b) is there any direct way to get maximum training sensitivity plus specificity threshold value? In raw and cloglog scales for example... Thank you!

>     2\. Do you have any specific questions about the internal workflow in ENMeval?

**Comment by andliszmmu** [comment]
Sorry, can I move up my question? ))

**Comment by ndimhypervol** [comment]
Hey sorry to have overlooked your question. Not sure why rasterPreds=FALSE
would eat up memory, or why it would give you rasters. It is supposed to
avoid predicting to rasters and just return the models and results tables.

For maxnet, the closest thing to the Java program's "raw" output is the
"exponential" output, but to make it match with raw I believe you need to
divide all values by the max value (but might be wrong).

Concerning thresholds, regardless of the output transformation should
result in the same omission rates. For example, if you find the 10%
quantile value of all predicted occurrences and threshold with that (the 10
percentile omission), it wouldn't matter whether it's raw or cloglog or
logistic because they all scale the same. ENMeval does not do the maxSSS
threshold because maximizing specificity (true negative rate) doesn't make
sense for presence-only SDMs, as there is no absence data. If you want to
find this value independently, you can use the evaluate() function in dismo
using the training data and the model.

Hope this helps! If you have more questions, let me know.

Jamie

**Comment by andliszmmu** [comment]
Thank you very much for the answer Jamie! Sorry, it was a misprint, I meant rasterPreds=TRUE everywhere. Well, al I understand correctly now - I get raw output with rasterPreds=TRUE option? And this is the only way to get it directly?

**Comment by ndimhypervol** [comment]
With ENMeval v0.3.x, the output rasters are raw predictions. You can make
cloglog or logistic predictions with predict() using the model objects in
e@models. The default should be cloglog when using Maxent 3.4.1.

Jamie

**Comment by andliszmmu** [comment]
Thank you

**Comment by fbocean** [comment]
Hi all,

thanks for this discussion which has been very helpful! 
I have a couple of questions and would be very grateful for an opinion. I hope it's okay to ask here.

I would like to try the method by Cory Merow, which if I understand correctly would include both
step 1: use "biased" background points which are sampled based on a sampling/detection probability distribution (I am using a rescaled KDE of reference group sightings from the same occurrence database) and
step 2: correcting predictions by factoring the bias out (i.e. dividing raw predictions by the sampling probability, in my case from the KDE, and then normalising them to sum to one)

This paper by Cory Merow et al. https://doi.org/10.1111/geb.12453 helped me understand the "factor bias out" method a bit better (both the main text and especially also the Maxent part in the supplementary material). If I understand correctly, it states both, that when Maxent is provided with an offset (i.e. bias grid), background points used in the model are sampled based on those probabilities (supplementary material: line 823 ff.) and that maxent considers the offset introduced by the bias file as a "nuisance" and therefore filters it out from the predictions. 

What I am not clear about when applying the method for swd input are some aspects of predicting and how it affects my evaluation statistics.
Given that my background points are just a sample of the area of interest, should I follow the approach by @andliszmmu above, and predict for the whole area (i.e. the area of my KDE raster) using a loop with the maxnet.predictRaster function, apply the factorbiasout method to the predictions of the whole background and then recalculate all my the evaluation metrics (as done above for AICc)?
Or should I be calculating the evaluation metrics only on those points that went in as model input (i.e. number of presences and number of background points, as ENMeval does automatically, but in my case I would need to tweak it to calculate the stats on the "corrected" predictions, e.g. using the user.eval function)?
And in fact, should I always be predicting over the whole area before calculating evaluation metrics from swd input?
Or is it dependent on the type of evaluation metric?

In case it's relevant: The approach I'm following is similar to the workflow suggested for kuenm. I'm first running many models with different settings based on cross validation using partitions of my incidental occurrence data. In a second step, I'd like to validate those models pre-selected in that first step (i.e. the most suitable based on a set of evaluation criteria) with a second occurrence data set which is a bit smaller, but based on actual survey data. 

I'm very sorry if this is a basic question and I hope it's not too far from the topic.

Thank you kindly
fb
