### ISSUE TITLE
Maxnet parallal Ubuntu memory allocation

### ISSUE THREAD

**Issue by Pgalante** [jamiemkass/ENMeval#60]
Using the same data (albeit rather large rasters), algorithm='maxent.jar' works fine, but algorithm='maxnet' crashes RStudio only when running in parallel. It seems that there is an issue with the RAM maxing out. I'm not sure if there is a fix, but we might want to let users know that this exists (Ubuntu 18.04). 
If RStudio does not crash I get this error:
Error in unserialize(socklist[[n]]) : error reading from connection
Suggestions to set ulimit -v [a lower amount] don't seem to work. It does work if I drastically limit the number of cores to use (3 is the most I can with this data).

**Comment by jamiemkass** [comment]
Wondering if this is still an issue with the new version, @Pgalante.

**Comment by narayanibarve** [comment]
Hi. Looks like there is memory problem in running the package in parallel. I am not sure if there is a problem with Java or memory management in ENMeval. But here is a error I have received when I run ENMEval 

** Running ENMeval v2.0.3 with maxent.jar v3.4.3 from dismo package v1.3.9 ***

  |=====                                                                 |   7%Error in rJava::.jarray(rowvals, dispatch = TRUE) :
  java.lang.OutOfMemoryError: Java heap space

**Comment by jamiemkass** [comment]
Narayani, please see the answer here for increasing the memory for maxent.jar. This should fix the issue:

https://stackoverflow.com/questions/15399796/rjava-memory-error
