### ISSUE TITLE
File in Temp Folder Issue when running in parallel (Error in file(fn, "rb))

### ISSUE THREAD

**Issue by keatonwilson** [jamiemkass/ENMeval#67]
Just ran into an issue that appear to have cropped up before (https://groups.google.com/forum/#!topic/Maxent/gnx5VJC5m4E). Running the ENMevaluate function on a fairly large data set across eastern US - error only crops up when running in parallel. Everything runs beautifully (though slow) when not in parallel.

Error in file(fn, "rb") : cannot open the connection
In addition: Warning message:
In file(fn, "rb") :
  cannot open file '/private/var/folders/hw/wppy3gb528d2gtbs46tq880c0000gn/T/RtmpJwczlb/raster/r_tmp_2019-03-22_113009_64410_84138.gri': No such file or directory

Any thoughts?

**Comment by Pgalante** [comment]
What operating system are you using? I get this error when I'm running Ububtu. As far as I dug into it (not terribly far), it's an issue with R parallelization in that environment.

**Comment by keatonwilson** [comment]
I'm running it on Mac OS Mojave - good to know it's happening on at least two OSs.

**Comment by hgfell** [comment]
I am having the exact same issue on Mac OS Mojave as well.

**Comment by keatonwilson** [comment]
Anybody have any solutions to this? Just had it crop up again, and am working towards a really big set of model building - need that parallelization!

**Comment by ndimhypervol** [comment]
Keaton,

Can you please try to install the dev version? Parallelization is
implemented in a different way, and it might not have this problem.

devtools::install_github("bobmuscarella/ENMeval@dev")

Jamie

**Comment by keatonwilson** [comment]
Installed dev version, but couldn't test parallelization because it broke other parts of the ENMevaluate function:

Running ENMeval v1.0.0 with legacy parameters. These will be phased out in the next version.

Error in dismo::kfold(occs, kgrp) : 
  argument "kgrp" is missing, with no default

**Comment by ndimhypervol** [comment]
Sorry, just fixed the error. Please reinstall and try again.
-----------------------------------------------------------
Jamie Kass, Ph.D.
Biodiversity and Biocomplexity Unit
Okinawa Institute of Science and Technology
Institutional email: jamie.kass@oist.jp
<http://andersonlab.ccny.cuny.edu>

**Comment by keatonwilson** [comment]
Back to having the original problem. See screenshot below. This was on MacOS 10.146 - also testing on a linux server at the moment. 

![Screen Shot 2019-09-30 at 1 50 14 PM](https://user-images.githubusercontent.com/31970388/65916011-738a9f00-e389-11e9-993b-0dfc1abb23f2.png)

**Comment by ndimhypervol** [comment]
I think this might be due to a permissions error. Have you considered using
maxnet? No temp folder problems with maxnet. Otherwise, I guess there might
be a way to make your own temp folder and assign it to maxent(). I could
make this a param you control from ENMeval.

**Comment by keatonwilson** [comment]
Huh. It seems fine when run non-parallel - it's essentially the same error I reported at the start of this thread. It looks like it's splitting the raster file into grids for each parallel process and then for some reason not able to read/find them? I'll try with maxnet here in a sec and see if that makes any difference. Thanks for the help!

**Comment by keatonwilson** [comment]
Similar error running maxnet on Mac OS 10.146 with the dev version - will try running non-parallel next. Let me know what else I might try!

<img width="797" alt="Screen Shot 2019-10-01 at 8 57 27 AM" src="https://user-images.githubusercontent.com/31970388/65979258-d469b400-e429-11e9-8aae-558099ce3263.png">

**Comment by keatonwilson** [comment]
FYI: Same data, same code. Finished perfectly without parallelization. 

<img width="782" alt="Screen Shot 2019-10-01 at 9 05 22 AM" src="https://user-images.githubusercontent.com/31970388/65979773-bbadce00-e42a-11e9-93e3-86c6c5056553.png">

**Comment by keatonwilson** [comment]
Also, for what it's worth: different set of issues running dev version with maxnet in parallel and not on a linux instance. 

![Screen Shot 2019-10-01 at 3 48 57 PM](https://user-images.githubusercontent.com/31970388/66006329-2a0e8280-e463-11e9-8525-1bf44e4d73e8.png)
![Screen Shot 2019-10-01 at 3 48 04 PM](https://user-images.githubusercontent.com/31970388/66006330-2a0e8280-e463-11e9-9ea4-5c056a0e1384.png)

**Comment by ndimhypervol** [comment]
Hm, not sure how to fix this. When running things in parallel, a number of different system processes occur that I am not too knowledgeable about. If you have any suggestions on what I migt do to fix these issues, please let me know!

**Comment by jamiemkass** [comment]
Closing this issue because the new version is now out, which may have fixed this problem.
