### ISSUE TITLE
Change the default number of iterations via userArgs

### ISSUE THREAD

**Issue by elgabbas** [jamiemkass/ENMeval#69]
Hello,

Is it possible to change the maxent's default number of iterations to a user-specific value through the `userArgs` argument? I used something like:
```
enmeval_results <- ENMevaluate(occ, env, method="block", n.bg=500,
                               categoricals=4, algorithm='maxent.jar',
                               userArgs = list(maximumiterations = "2000"))
```
but it gives me this error:
`Error in ENMevaluate(occ, env, method = "block", n.bg = 500, categoricals = 4,  :    The maxent argument given is not implemented in ENMeval or is misspelled.`

I checked the source code of ENMevaluate function and I think maximumiterations is implemented. Could you please provide some information on how should I provide the `userArgs` correctly?

Cheers,
Ahmed

**Comment by elgabbas** [comment]
Hello Bob @bobmuscarella,

I think I was able to solve this by editing the `ENMevaluate` function locally.
To make it works, I added `userArgs = NULL` as one of the function argument and removed code on line 18: `userArgs <- list(...)`.

Also, I encountered errors when using the package in parallel on Linux (Centos) cluster, which requires some modifications to the functions as well. Does the package work fine on windows and Linux distributions?

Cheers,
Ahmed

**Comment by bobmuscarella** [comment]
Hi Ahmed -
Thanks for this inputs. Glad you figured out a solution for the userArgs.
As far as I know the package has been working fine on windows and linux
distributions but I haven't thoroughly tested it.  I have heard of some
issues with running in parallel on linux but, if i remember correctly, i
think it had more to do with the parallel packages being called than
ENMeval per se.
Bob

**Comment by elgabbas** [comment]
Yes, the issue on Linux seems to be not an ENMeval issue _per se_.

In my case, this was more related to the use of `parallel` package instead of `snow`. I have to replace these two lines of code:
https://github.com/bobmuscarella/ENMeval/blob/325e686b6f72413a443e9c8291e63867bd9ebd13/R/tuning.R#L78-L79

with:

```
c1 <- snow::makeSOCKcluster(numCores, outfile="")
snow::clusterEvalQ(c1, {
    Sys.setenv(NOAWT=TRUE)
    options(java.parameters = "-Xmx20g", stringsAsFactors = FALSE)
    library(foreach, quietly = TRUE)
    library(rJava, quietly = TRUE)
    library(dismo, quietly = TRUE)
    library(raster, quietly = TRUE)
    library(snow, quietly = TRUE)
    library(doSNOW, quietly = TRUE)
    .jinit()
})
```
to make it works for me!

**Comment by bobmuscarella** [comment]
Thanks for sharing! This could be useful for others.

**Comment by cmontalvo-mancheno** [comment]
Hey ENMeval developers,

I am using ENMeval v. 2.0.1 to select best maxent models across multiple feature combinations and values for the regularization multiplier. Given that @elgabbas solution to change the maxent's default number of iterations to a user-specific value was for a previous version, I wonder if this was added/fixed in the current version? Could you please tell me how I do this in the current version?

Cheers,
Cristian

p.s. Below is my code :)

`ENMevaluate(occs = suit_1_devil_occs %>% select(x:y),
            envs = bioreg_08,
            bg = suit_1_devil_bg,
            tune.args = list(fc = c("L", "LQ"), rm = 1:2),
            partitions = "user",
            user.grp = list(occs.grp = suit_1_devil_occs %>%
                              select(spatial_block) %>%
                              pull(),
                            bg.grp = suit_1_devil_bg %>%
                              select(spatial_block) %>%
                              pull()),
            algorithm = "maxent.jar",
            other.settings = list(abs.auc.diff = TRUE,
                                  pred.type = "logistic",
                                  validation.bg = "full"))`

**Comment by jamiemkass** [comment]
@cmontalvo-mancheno In ENMeval 2.0.x, add this to the list in the `other.settings` argument in `ENMevaluate()`:
`other.args = "maximumiterations=10000"`
That should feed this user argument directly into maxent.jar. Please let me know if it works or not. Not sure how you'd check this without the html, but perhaps this info is stored in the model object.

Jamie

**Comment by cmontalvo-mancheno** [comment]
Hey ENMeval developers,

I am using your package v. 2.0.1 to evaluate models for my target species across multiple feature combination and values of regularization multiplier. Given that elgabbas' solution to change the maxent's default number of iterations to a user-specific value was for a previous version, I think, I wonder if this was added/fixed to current version? Could you please tell me how I can do this in ENMeval 2.0.1?

Cheers,
Cristian

p.s. below is an example of my code :)

```
ENMevaluate(occs = suit_1_devil_occs %>% select(x:y),
            envs = bioreg_08,
            bg = suit_1_devil_bg,
            tune.args = list(fc = c("L", "LQ"), rm = 1:2),
            partitions = "user",
            user.grp = list(occs.grp = suit_1_devil_occs %>%
                              select(spatial_block) %>%
                              pull(),
                            bg.grp = suit_1_devil_bg %>%
                              select(spatial_block) %>%
                              pull()),
            algorithm = "maxent.jar",
            other.settings = list(abs.auc.diff = TRUE,
                                  pred.type = "logistic",
                                  validation.bg = "full"))
```

**Comment by Himantopus** [comment]
Hello, my Maxent models in ENMeval  v2.0.4 are not converging after the default 500 iterations and I'd like to increase maximumiterations, but I can not do it. I tried the solution of @jamiemkass but it doesn't work. Any suggestions? Here's my code:

 `Model <- ENMevaluate(occs = Train_dat, 
                     bg = bg,
                     partitions ='user', 
                     user.grp = blocks,
                     RMvalues=2, 
                     fc=c('LQP'), 
                     algorithm='maxent.jar',
                     other.settings = list(validation.bg = 'partition',
                                           other.args = "maximumiterations=10000"))`

I also tried to write `other.args = list(maximumiterations = 10000)` and all other formatting possibilities that I could imagine.

Thanks

**Comment by jamiemkass** [comment]
@Himantopus Thanks for using the pkg. I'll look into this sometime this week and get back to you.

**Comment by jamiemkass** [comment]
Sorry this took so long. In version 2.0.5, you can specify the maximumiterations arg like this:

    ENMevaluate(occs, envs, bg, 
            tune.args = list(fc = c("L","LQ"), rm = 1:2), 
            partitions = "block", partition.settings = ps,
            algorithm = "maxent.jar", categoricals = "biome", overlap = TRUE,
            other.settings = list(path = "/Users/kass/Downloads/results", 
            other.args = c("jackknife=TRUE", "responsecurves=TRUE", "maximumiterations=10000")))
            
Just make sure to leave no spaces between the = and the arg name and value, because for some reason it errors if you do.

**Comment by daniellesloan** [comment]
Hi Jamie,  I am trying add "removeDuplicates=FALSE" using other.settings and other.args but I can't get it to work. Any suggestions? Here is my code:

enmeval_results  <- ENMevaluate(pres, # presence records
                                env, # environmental layers
                                bg = bgp, # background points 
                                tune.args = list( # tuning arguments
                                  fc = c("L","LQ","H", "LQH", "LQHP", "LQHPT"), 
                                  rm = 1:5), # regularisation multiplier
                                partitions = partition,
                                algorithm = "maxent.jar", 
                                other.settings = list(other.args = c("removeDuplicates=FALSE")))
Thanks, 

Danielle

**Comment by narayanibarve** [comment]
Can you please give a link to version 2.0.5 ? I tried changing number of maximum iteration in 2.0.4, but it does not work.

**Comment by jamiemkass** [comment]
You can run `remotes::install_github("jamiemkass/ENMeval@v205_draft")` to install v2.0.5.
