### ISSUE TITLE
Error when using Enmeval 2.0.0

### ISSUE THREAD

**Issue by momeni133** [jamiemkass/ENMeval#90]
Hello,
When I run the ENMevaluate() function using ENMeval 2.0.0 if I choose "maxent.jar" as an algorithm to be used, I receive this error: 
Error in { : 
  task 1 failed - "could not find function "modelTune.maxentJar""

When I choose "maxnet" as an algorithm to be used, I receive the below error:
Error in { : task 1 failed - "could not find function "modelTune.maxnet""

any helps would be so appreciated.
Thanks

**Comment by jamiemkass** [comment]
Thanks for using the package. I am confused by your error because references to those functions no longer exist in the new version. Please make sure you've properly installed the new version.

**Comment by momeni133** [comment]
Hi Jamie
Thanks for your quick response. 
After deleting and re-installing v2.0.0, the error changed to:

"Error in ENMevaluate(occ = points, envs = predictorsEW, bg = background,  : 
  This argument was deprecated. If you want to avoid generating model prediction rasters, include predictor variable values in the occurrence and background data frames (SWD format). See Details in ?ENMevaluate for more information."

It doesn't matter if I put the rasterPreds = TRUE or False and if I use SWD or just coordinates. I always receive this error.

I am using this code to tune the MaxEnt:
ENMevaluate(occ=points, envs=predictorsEW, bg= background, 
                                           partitions = "checkerboard2",tune.args=list(fc = c("L","H", "LQ", "LQH", "LQHP"), rm = 0.5:10),
                                           bin.output = FALSE, parallel = TRUE, rasterPreds = TRUE, algorithm = 'maxent.jar', updateProgress=TRUE)

**Comment by jamiemkass** [comment]
Try running it without the argument rasterPreds, and thus leaving it at the default of NULL. This argument is deprecated, and should be excluded. The function makes raster predictions automatically, but to run without rasters, simply put the result of raster::extract(envs, occs) and raster::extract(envs, bg) in place of occs and bg, and leave envs NULL.

I will change the language of the error to make this less confusing, so thanks for pointing this out.

**Comment by momeni133** [comment]
Thanks Jamie
The problem has been solved.

Many thanks

**Comment by jamiemkass** [comment]
Great! Glad it worked out.
