### ISSUE TITLE
RM zero

### ISSUE THREAD

**Issue by gepinillab** [jamiemkass/ENMeval#91]
Hi Jamie,

Thanks for a post of Lux Tres Puntos in the Spanish ENM group (https://www.facebook.com/groups/245646162181621/permalink/3675466495866220/), iI think that it is a good idea to add an error message if there is a regularization multiplier equal to zero. The error message that she got is the following:

`Error: from glmnet Fortran code (error code 10000); All penalty factors are <= 0`

She fixed it by not including zero in the combinations to run.

Best,
Gonzalo

**Comment by jamiemkass** [comment]
Addressed this. Thanks~
