### ISSUE TITLE
Error in ENMevaluate: non-conformable arguments

### ISSUE THREAD

**Issue by olijw** [jamiemkass/ENMeval#92]
Hi,

I'm trying to run the ENMevaluate function and have consistently run up against the same problem on both Windows and Linux: 'Error in mm %*% object$betas : non-conformable arguments'. I haven't been able to find any useful information on it at all online (which makes me worry I'm doing something wrong) so thought I'd ask about it here. Any help you can give would be very gratefully received!

Thanks,

Oli

The code I've used is very closely based on the vignette example. 'locs' is a dataframe with three columns: longitude, latitude and presence/absence (1/0) for a species 'sp.n'. 'envs' is a raster stack of 10 bioclimatic variables.

> occs=subset(locs,locs[,sp.n]==1)[,1:2]
> bg=subset(locs,locs[,sp.n]==0)[,1:2]
> blocks=get.block(occs,bg)
>
> eval1=ENMevaluate(occs, envs, bg, method='block', RMvalues=seq(0.5,5,0.5), fc=c('L','LQ','H','LQH','LQHP'), rasterPreds=F)
*** Running ENMevaluate using maxnet v.0.1.2 ***
Doing evaluations using spatial blocks...
There are 286 background records with NA for at least one predictor variable.
                  Removing these records from analysis, resulting in 9714 records...
  |=============================================================                               |  66%Error in mm %*% object$betas : non-conformable arguments
> traceback()
5: predict.maxnet(model, data[p == 0, , drop = FALSE], type = "exponent", 
       clamp = F)
4: maxnet::maxnet(p, x, f = maxnet::maxnet.formula(p = p, data = x, 
       classes = args.i[1]), regmult = as.numeric(args.i[2]))
3: modelTune.maxnet(pres, bg, env, nk, group.data, args[[i]], rasterPreds, 
       clamp)
2: tuning(occ, env, bg.coords, occ.grp, bg.grp, method, algorithm, 
       args, args.lab, categoricals, aggregation.factor, kfolds, 
       bin.output, clamp, alg, rasterPreds, parallel, numCores, 
       progbar, updateProgress, userArgs)
1: ENMevaluate(occs, envs, bg, method = "block", RMvalues = seq(0.5, 
       5, 0.5), fc = c("L", "LQ", "H", "LQH", "LQHP"), rasterPreds = F)
>

**Comment by jamiemkass** [comment]
Oli,

Thanks for using ENMeval. Similar errors have been known to pop up when using hinge features, so try running ENMevaluate() without them and see if the problem goes away. If it does, run the same models with hinge features using the maxent.jar software and it should work.

I forget if it's the same error or not, but there was a common error with categorical variables when a category was not represented by enough records. Adding occurrences to the background usually fixes this issue, which has a tendency to occur when the occurrence dataset is big. A new version of maxnet added a parameter to do this, and the new ENMeval 1.9.0 does this automatically, so if you are still having issues, try the new version. 

Hope this helps,

Jamie

**Comment by olijw** [comment]
Hi Jamie,

Thanks very much for the response - you were right, excluding hinge features got the function working, and maxent.jar was able to handle them when I brought them back in. It is a shame that the maxnet version couldn't do it - I'd planned to run this on a remote cluster where independence from the Java program would have been useful - but it's certainly good to have it working now!

Thanks again for the help.

All the best,

Oli

**Comment by jamiemkass** [comment]
Glad to help! Yes, hopefully future versions of maxnet will reduce the possibility of this error.
