### ISSUE TITLE
CLOGLOG response curves

### ISSUE THREAD

**Issue by LuzReyesE** [jamiemkass/ENMeval#93]
Hello!
I am using ENMevaluate to generate distribution models. I am converting the selected models to a CLOGLOG output through the "predict" function and everything turns out very well.

 I would also like to see the response curves, but in CLOGLOG type. However, I don't know how to do it. I'm trying through the "response" function, but it doesn't work directly on the converted model since it is no longer of type "MaxEnt".
 I would like to try the "fun" argument, but I don't understand how it works and I can't find any examples. https://www.rdocumentation.org/packages/dismo/versions/1.3-3/topics/response

I hope someone can help me, thank you...

**Comment by jamiemkass** [comment]
I am pretty sure that adding the parameter `type = "cloglog"` to `response()` should work for maxnet models.

**Comment by LuzReyesE** [comment]
Thanks for your answer ...
  The problem is that I did my models with "maxent.jar".

**Comment by jamiemkass** [comment]
Ah okay, in that case, do `response(m, p, args = "outputformat=cloglog")`, where m is the model object.

**Comment by LuzReyesE** [comment]
Thanks for your answer, 
  It worked very well.
