### ISSUE TITLE
Error in ENMevaluate 

### ISSUE THREAD

**Issue by RussellGrayxd** [jamiemkass/ENMeval#94]
When running ENMevaluate in the past I have never had an issue. Now I am running it on some SE Asian species and suddenly I'm running this error:

*** Running ENMevaluate using Maxent 3.4.1 via dismo 1.3.3 ***
Doing random k-fold evaluation groups...
There are 28 occurrence records with NA for at least
                  one predictor variable. Removing these records from analysis,
                  resulting in 41 records...
There are 222 background records with NA for at least one predictor variable.
                  Removing these records from analysis, resulting in 9778 records...
  |==                                                                                             |   2%This is MaxEnt version 3.4.1 
Error: Error reading files
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'C:\Users\Russe\AppData\Local\Temp\Rtmp4MwvV7/raster/maxent/9495393317/species.lambdas': No such file or directory

So to me it looks like the function is trying to save to a temporary file with a wonky path with both "/" and "\". I checked the file path and there is nothing wrong with it, just something wrong with the way the function is trying to access it. I have no idea how to change the temp path for the file output. 

Anyone know how to fix this? I'm stumped.

**Comment by RussellGrayxd** [comment]
Ok so I installed the development version and the problem magically went away. Neat!

**Comment by jamiemkass** [comment]
Thanks for posting this. So installing the new ENMeval did the trick? That's good to know, but kind of a mystery what was happening. I would also like to remind you to update your Maxent to 3.4.4 because some bugs were fixed recently.

Jamie

**Comment by RussellGrayxd** [comment]
I am having the same issue with the dismo package now, so I suspect it may be Maxent? Although I ran the same code with different species from a month ago and both ENMevaluate and maxent() function work. I'm stumped....
--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 

0934581341 | ***@***.***://www.rjgrayecology.com/
705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168

 |
| 
 |
|  |

 

    On Thursday, April 22, 2021, 05:32:33 p.m. GMT+7, Jamie M. Kass ***@***.***> wrote:  
 
 


Thanks for posting this. So installing the new ENMeval did the trick? That's good to know, but kind of a mystery what was happening. I would also like to remind you to update your Maxent to 3.4.4 because some bugs were fixed recently.

Jamie

**Comment by jamiemkass** [comment]
Sometimes I get this error when the rasters in the R environment are not loaded into memory, and I need to reload them with `raster()`. You can check this by trying to plot them -- if they don't plot, you know you need to reload.

**Comment by RussellGrayxd** [comment]
Nope, everything is loaded and plotting. Projections and everything are all matching with the bg points and occurrences. No clue what's going on yet, but I will update once I find out (hopefully soon). 
--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 

0934581341 | ***@***.***://www.rjgrayecology.com/
705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168

 |
| 
 |
|  |

 

    On Friday, April 23, 2021, 07:44:43 a.m. GMT+7, Jamie M. Kass ***@***.***> wrote:  
 
 


Sometimes I get this error when the rasters in the R environment are not loaded into memory, and I need to reload them with raster(). You can check this by trying to plot them -- if they don't plot, you know you need to reload.

**Comment by baltazargch** [comment]
Hi @RussellGrayxd and @jamiemkass , 

Did you find out what the problem is? I ran into the same problem today. Updated ENMeval from 2.0.0 to 2.0.1 with no luck. I also tried downgrading ENMeval to 0.3.0, and tried to used dismo::maxent() function but the same error occurs. I'm using Maxent v3.4.4 as suggested. Any ideas? 

Thanks

**Comment by jamiemkass** [comment]
ENMeval simply calls dismo::maxent(), so if you cannot use this function outside of ENMeval, it's either a dismo or maxent.jar issue. Can you post the error you're getting?

**Comment by baltazargch** [comment]
@jamiemkass thanks for the response, 

I am running ENMevaluate without raster (SWD format). The error I'm getting is this: 

*** Running initial checks... ***

* Variable values were input along with coordinates and not as raster data, so no raster predictions can be generated and AICc is calculated with background data for Maxent models.
* Model evaluations with spatial block (4-fold) cross validation and lat_lon orientation...

*** Running ENMeval v2.0.0 with maxent.jar v3.4.4 from dismo package v1.3.3 ***

  |==                                                                              |   2%This is MaxEnt version 3.4.4 
Error: Error reading files
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file '/tmp/RtmpC5EFHk/raster//maxent/9597691761/species.lambdas': No such file or directory

The code is:
```
 m <- ENMevaluate(
    occs= occs.SWD,
    bg = x,
    algorithm = "maxent.jar",
    partitions = "block",
    parallel = T,
    numCores = 8,
    tune.args = list(
      fc=c("L","LQ","H","Q","LQH","LQHP"),
      rm=c(seq(0.5,4,0.5)
           )
      )#end args
  ) #end enmeval
```
as you say, it seems to be something with the maxent.jar or dismo function. Here is my session info: 

R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.5.so

locale:
 [1] LC_CTYPE=en_US.UTF-8          LC_NUMERIC=C                 
 [3] LC_TIME=es_AR.UTF-8           LC_COLLATE=en_US.UTF-8       
 [5] LC_MONETARY=es_AR.UTF-8       LC_MESSAGES=en_US.UTF-8      
 [7] LC_PAPER=es_AR.UTF-8          LC_NAME=es_AR.UTF-8          
 [9] LC_ADDRESS=es_AR.UTF-8        LC_TELEPHONE=es_AR.UTF-8     
[11] LC_MEASUREMENT=es_AR.UTF-8    LC_IDENTIFICATION=es_AR.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ENMeval_2.0.1  magrittr_2.0.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7       raster_3.4-13    tidyselect_1.1.1 lattice_0.20-44  R6_2.5.0        
 [6] rlang_0.4.11     foreach_1.5.1    fansi_0.5.0      dplyr_1.0.7      tools_4.1.0     
[11] grid_4.1.0       dismo_1.3-3      utf8_1.2.1       DBI_1.1.1        iterators_1.0.13
[16] ellipsis_0.3.2   assertthat_0.2.1 tibble_3.1.2     lifecycle_1.0.0  crayon_1.4.1    
[21] rJava_1.0-4      purrr_0.3.4      vctrs_0.3.8      codetools_0.2-18 glue_1.4.2      
[26] sp_1.4-5         compiler_4.1.0   pillar_1.6.1     generics_0.1.0   pkgconfig_2.0.3

**Comment by jamiemkass** [comment]
Could you please try restarting the R session and trying again? Seems maxent.jar may be looking for something that's not there, and perhaps that may fix it. You're not using rasters in the current analysis, so this error is a little weird.

**Comment by baltazargch** [comment]
@jamiemkass Same thing happened, after restarting the R session. I also tried from the MaxEnt GUI and the model ran without errors. Could be something from dismo package?

**Comment by baltazargch** [comment]
@jamiemkass I found what was causing the error. I have some '-Inf' values for some predictors in the originals files for occurences and background data. Once I eliminated this records, the code worked fine. Sorry for the troubles and thanks for the response. Everything is running smoothly now.

**Comment by jamiemkass** [comment]
Very strange that such a problem would cause that error. I guess maxent.jar is filtering those records out when dismo may not be for some reason. It's weird because dismo just calls maxent.jar. I can put in a filter in ENMeval to remove the Inf values and inform the user for the next version. Glad you got it fixed.
