### ISSUE TITLE
?ENMevaluate (2.0.0) doesn't provide help in RStudio 1.4

### ISSUE THREAD

**Issue by tinsman** [jamiemkass/ENMeval#95]
I wanted to try out all of the amazing new features in ENMeval 2.0.0, but I'm having trouble accessing the help info when I load the package in Rstudio. I installed the package using devtools and install_github. It gives me a message about using legacy formatted inputs when I try to run some old ENMeval code, so I think it's working. I can't call up the help features using ? or the new vignette using vignette(package = "ENMeval").

Thanks for all your hard work! I'm so excited to get this working.

**Comment by jamiemkass** [comment]
Glad you're excited about v2! If `ENMevaluate()` says you're using legacy parameters, it means you need to change them to the new ones. The code will still work though. Very curious why the help docs are not displaying for you. Can you please post the error it gives? Thanks.

**Comment by tinsman** [comment]
Okay, weird, help (`?ENMevaluate`) is working now, so it must have been something on my end. However, when I type `vignette(package = 'ENMeval')` I get:
`no vignettes found`

**Comment by jamiemkass** [comment]
Can you please try installing with `build_vignettes = TRUE`? This might fix it. If it does, I will make a note on the README.

**Comment by tinsman** [comment]
That did it, after a couple of tries. Thanks for the advice, Jamie!

Also, for future readers if you get the "Internal Server Error" when you want help, detaching the package, reinstalling, and restarting my machine is what I think worked for me.

**Comment by jamiemkass** [comment]
Thanks for the feedback! Glad it worked in the end.
