### ISSUE TITLE
Warning: Error in : 'corrected.var' is not an exported object from 'namespace:ENMeval'

### ISSUE THREAD

**Issue by aandishah** [jamiemkass/ENMeval#98]
Hello!

I have been having issues trying to run the Wallace (https://wallaceecomod.github.io/) on R. It was working alright until the ENMEval package got updated on 18th May. (This is when also when there was a new R package 4.1.0)

The project works fine for all the steps until you get to the part where you run the BIOCLIM model. At this point the screen greys out and I am unable to select anything on the page. On the RStudio terminal I get an error stating: 
Warning: Error in : 'corrected.var' is not an exported object from 'namespace:ENMeval'
  2: shiny::runApp
  1: run_wallace

The ENMeval, shiny, wallace packages are all installed and updated, along with an other required files such as rgdal, devtools, and dismo. However, this error still persists. I know some of others who said they were having issues based on the browser the link was opening on - but I have tried on Chrome, Firefox and Edge but to no avail. I have also run it through R GUI, R CMD and using different Cran mirrors. I have also tried running the package on the previous version of R - 4.0.5 but that doesn't seem to solve the issue. 

If anyone could let me know what solutions could be provided to resolve this issue, would be super grateful!

Thank you!. 

Attatched is the Browser image at the point of error and the corresponding RStudio Terminal 
![image](https://user-images.githubusercontent.com/81915325/119048538-5d31bc80-b98d-11eb-8227-d12b11b24887.png)

**Comment by jamiemkass** [comment]
Thanks for pointing this out. The corrected.var() function was left out of the NAMESPACE, but I added it back in for the v2_cran branch. Please install ENMeval using this code:
`devtools::install_github("jamiemkass/ENMeval@v2_cran")`
and rerun Wallace, then please let me know if this fixes the issue. I'll update the CRAN version if it does.

Jamie

**Comment by gepinillab** [comment]
Hi @aandishah,

Please use:
`remotes::install_github("wallaceecomod/wallace")`

I explain a little bit more about the problem here:
https://github.com/wallaceEcoMod/wallace/issues/350

Thanks for letting us know about this issue.

Best,
Gonzalo

**Comment by gepinillab** [comment]
Hi @aandishah,

The Wallace version that fixes the problem is on CRAN (https://cran.r-project.org/web/packages/wallace/index.html). Please update Wallace and let us know if this fixes the problem.

Best,
Gonzalo

**Comment by aandishah** [comment]
> Thanks for pointing this out. The corrected.var() function was left out of the NAMESPACE, but I added it back in for the v2_cran branch. Please install ENMeval using this code:
> `devtools::install_github("jamiemkass/ENMeval@v2_cran")`
> and rerun Wallace, then please let me know if this fixes the issue. I'll update the CRAN version if it does.
> 
> Jamie

Hello, 

I have this version installed but its still causing the greying error

**Comment by jamiemkass** [comment]
Did you install the new version of Wallace from CRAN? That should fix it.

2021年5月27日(木) 0:07 aandishah ***@***.***>:
