### ISSUE TITLE
Convert ENMevaluation objects from version 0.3.1 to version 2.0

### ISSUE THREAD

**Issue by plantarum** [jamiemkass/ENMeval#99]
I have a large project with ENMevaluation objects saved in Rda format. i.e., 

```
eval.n.1920<-ENMevaluate(vr1920, env1920, RMvalues = seq(0.5, 8, 0.5), 
                         aggregation.factor=c(2, 4), n.bg=10000, 
                         method='checkerboard2', parallel=TRUE, 
                         algorithm='maxent.jar')
save(eval.n.1920, "data/evaln1920.rda")
```

This work was done prior to the release of ENMevaluate 2.0.0, and now when I try to reload the objects I'm getting errors due to format mismatches. None of my saved objects have a `tune.settings` slot, and there may be other changes as well. It looks like the rest of the data is still there (I hope).

Is there way to retroactively update `ENMevaluation` objects to conform to the new class definition? I have the code that was used to create them, but it will take quite a while to rerun it all.

**Comment by jamiemkass** [comment]
Thanks so much for the input. This is something that I overlooked when developing the new version, but should be included for cases like this. I think I will add a function that converts old ENMevaluation objects to new ones in the update 2.0.1. This should be up on CRAN by mid-June. Until then, you could run the analysis over again with the new package version, but if this is not an option, please wait for the update.

**Comment by plantarum** [comment]
Thanks Jamie.

I have figured out how to install the previous release via the 
`remotes` package, so that solves my immediate problem.

I'm not sure how big a problem the format change actually is. It 
causes an error when you try to print the object, since it's 
missing the new slots. Maybe it's enough to short-circuit the 
print method (and any other functions that require the new slots) 
to display a warning and exit before they get to the code that 
generates an error?

Whatever you decide, thanks for following up!

**Comment by jamiemkass** [comment]
Tyler, I actually just implemented a new function called
ENMevaluation_convert() and got the CRAN version updated, so install it and
give it a try. Thanks for bringing up this issue and helping to improve the
pkg!

Jamie

2021年6月12日(土) 3:55 Tyler Smith ***@***.***>:
